"""The audit emitter: what one `emit()` call writes, refuses, and never breaks.

Requirements exercised: FR-A-02 (fixed schema, a write missing a required field
is rejected), FR-A-04 (no student data), FR-A-11 (logging failure never fails
the user action), X-4 (a student's email, address and browser are never stored)
and X-5 (the trace id is generated by the server, the client's id is kept as
untrusted context only).
"""

import logging
import uuid
from unittest import mock

from django.conf import settings
from django.contrib.auth.models import AnonymousUser
from django.db import DatabaseError, IntegrityError, connection, transaction
from django.test import RequestFactory, TestCase, TransactionTestCase, override_settings

from AutoGrader.request_context import get_request_id, reset_request_id, set_request_id
from classrooms.models import School
from users.models import CustomUser, UserTypes

from .context import current_trace_id, trace_context
from .emitter import AuditValidationError, emit
from .enums import (
    STUDENT_RECORD_ACTIONS,
    ActorRole,
    AuditAction,
    AuditOutcome,
    ErrorClass,
    RetentionClass,
)
from .metadata import ALLOWED_KEYS, metadata_allowlist_for
from .models import AuditEvent

PASSWORD = "pw-12345678"  # nosec  # pragma: allowlist secret


def make_user(email, user_type=UserTypes.TEACHER, school=None):
    return CustomUser.objects.create_user(
        email=email,
        password=PASSWORD,
        user_type=user_type,
        first_name="Test",
        last_name="User",
        school=school,
    )


def call(**over):
    """A minimal valid emit() call."""
    args = {"actor": None, "target_type": "Assignment", "target_id": uuid.uuid4()}
    args.update(over)
    return emit(AuditAction.ASSIGNMENT_COPY, **args)


def request(**meta):
    return RequestFactory().get("/", **meta)


class WhatOneEventRecordsTest(TestCase):
    school: School
    teacher: CustomUser
    student: CustomUser

    @classmethod
    def setUpTestData(cls):
        cls.school = School.objects.create(name="Emit School")
        cls.teacher = make_user("emit.teacher@emit.edu", school=cls.school)
        cls.student = make_user("emit.kid@example.com", UserTypes.STUDENT)

    def test_one_call_writes_exactly_one_complete_row(self):
        target = uuid.uuid4()
        event = emit(
            AuditAction.ASSIGNMENT_COPY,
            actor=self.teacher,
            target_type="Assignment",
            target_id=target,
            request=request(REMOTE_ADDR="203.0.113.9", HTTP_USER_AGENT="Browser/1.0"),
            metadata={"item_count": 3},
        )
        self.assertEqual(AuditEvent.objects.count(), 1)
        row = AuditEvent.objects.get()
        self.assertEqual(row.pk, event.pk)
        self.assertEqual(row.action, "ASSIGNMENT_COPY")
        self.assertEqual(row.actor_id, self.teacher.id)
        self.assertEqual(row.actor_role, ActorRole.TEACHER)
        self.assertEqual(row.actor_email, "emit.teacher@emit.edu")
        self.assertEqual(row.school_id, self.school.id)
        self.assertEqual(row.target_type, "Assignment")
        self.assertEqual(row.target_id, target)
        self.assertEqual(row.outcome, AuditOutcome.SUCCESS)
        self.assertIsNone(row.error_class)
        self.assertEqual(row.source_ip, "203.0.113.9")
        self.assertEqual(row.user_agent, "Browser/1.0")
        self.assertEqual(row.metadata, {"item_count": 3})
        self.assertEqual(row.retention_class, RetentionClass.GENERAL)
        self.assertIsNotNone(row.occurred_at)

    def test_every_user_type_maps_to_its_role(self):
        for user_type, role in (
            (UserTypes.TEACHER, ActorRole.TEACHER),
            (UserTypes.SCHOOL_ADMIN, ActorRole.SCHOOL_ADMIN),
            (UserTypes.SUPER_ADMIN, ActorRole.SUPER_ADMIN),
            (UserTypes.STUDENT, ActorRole.STUDENT),
        ):
            with self.subTest(user_type=user_type):
                user = make_user(f"role.{str(user_type).lower()}@emit.edu", user_type)
                self.assertEqual(call(actor=user).actor_role, role)

    def test_no_actor_is_a_system_event_with_no_identity(self):
        event = call(actor=None)
        self.assertEqual(event.actor_role, ActorRole.SYSTEM)
        self.assertIsNone(event.actor_id)
        self.assertIsNone(event.actor_email)

    def test_an_anonymous_visitor_is_recorded_as_no_identity(self):
        event = call(actor=AnonymousUser())
        self.assertEqual(event.actor_role, ActorRole.SYSTEM)
        self.assertIsNone(event.actor_id)

    def test_the_actor_is_captured_as_values_and_the_role_is_frozen_at_write_time(self):
        user = make_user("frozen@emit.edu", UserTypes.TEACHER, self.school)
        event = call(actor=user)
        user_id = user.id
        CustomUser.objects.filter(pk=user_id).update(user_type=UserTypes.SCHOOL_ADMIN)
        user.delete()
        event.refresh_from_db()
        self.assertEqual(event.actor_id, user_id)
        self.assertEqual(event.actor_role, ActorRole.TEACHER)
        self.assertEqual(event.actor_email, "frozen@emit.edu")

    def test_an_individual_teacher_has_no_licence(self):
        individual = make_user("solo@example.com")
        self.assertIsNone(call(actor=individual).school_id)

    def test_an_explicit_licence_and_department_are_recorded(self):
        """A super admin acting on behalf of a licence names it."""
        admin = make_user("root@emit.edu", UserTypes.SUPER_ADMIN)
        licence, department = uuid.uuid4(), uuid.uuid4()
        event = call(actor=admin, school_id=licence, department_id=department)
        self.assertEqual(event.school_id, licence)
        self.assertEqual(event.department_id, department)

    def test_the_outcome_and_error_class_are_recorded_for_a_failure(self):
        event = call(
            actor=self.teacher,
            outcome=AuditOutcome.FAILURE,
            error_class=ErrorClass.PROVIDER,
            reason_code="PROVIDER_TIMEOUT",
        )
        self.assertEqual(event.outcome, AuditOutcome.FAILURE)
        self.assertEqual(event.error_class, ErrorClass.PROVIDER)
        self.assertEqual(event.reason_code, "PROVIDER_TIMEOUT")

    def test_before_and_after_are_stored_when_given_and_null_when_not(self):
        event = call(
            actor=self.teacher,
            before={"item_count": 1},
            after={"item_count": 2},
        )
        self.assertEqual(event.before, {"item_count": 1})
        self.assertEqual(event.after, {"item_count": 2})
        plain = call(actor=self.teacher)
        self.assertIsNone(plain.before)
        self.assertIsNone(plain.after)

    def test_a_target_without_an_id_is_allowed(self):
        self.assertIsNone(call(actor=self.teacher, target_id=None).target_id)

    def test_a_string_uuid_target_id_is_accepted(self):
        target = uuid.uuid4()
        self.assertEqual(
            call(actor=self.teacher, target_id=str(target)).target_id, target
        )


class StudentDataTest(TestCase):
    """X-4 and FR-A-04: a student's identity, address and browser are never
    stored, whatever the call site passes."""

    student: CustomUser

    @classmethod
    def setUpTestData(cls):
        cls.student = make_user("kid.real.name@example.com", UserTypes.STUDENT)

    def test_a_student_event_carries_no_email_address_or_browser(self):
        event = call(
            actor=self.student,
            request=request(REMOTE_ADDR="198.51.100.4", HTTP_USER_AGENT="KidBrowser/2"),
        )
        self.assertEqual(event.actor_role, ActorRole.STUDENT)
        self.assertEqual(event.actor_id, self.student.id)
        self.assertIsNone(event.actor_email)
        self.assertIsNone(event.source_ip)
        self.assertIsNone(event.user_agent)

    def test_the_student_email_appears_nowhere_in_the_stored_row(self):
        event = call(
            actor=self.student,
            request=request(REMOTE_ADDR="198.51.100.4"),
            metadata={"item_count": 1},
        )
        stored = " ".join(
            str(getattr(event, f.name)) for f in AuditEvent._meta.get_fields()
        )
        self.assertNotIn("kid.real.name", stored)

    def test_an_email_smuggled_in_metadata_never_reaches_the_table(self):
        key = sorted(ALLOWED_KEYS)[0]
        event = call(actor=self.student, metadata={key: "kid.real.name@example.com"})
        self.assertEqual(event.metadata, {})

    def test_a_student_event_survives_a_student_who_is_later_deleted(self):
        event = call(actor=self.student)
        student_id = self.student.id
        self.student.delete()
        event.refresh_from_db()
        self.assertEqual(event.actor_id, student_id)


class RequestContextTest(TestCase):
    def setUp(self):
        self.teacher = make_user("ctx.teacher@example.org")

    def test_an_invalid_source_address_is_stored_as_null(self):
        event = call(actor=self.teacher, request=request(REMOTE_ADDR="not-an-ip"))
        self.assertIsNone(event.source_ip)

    def test_no_request_means_no_address_or_browser(self):
        event = call(actor=self.teacher)
        self.assertIsNone(event.source_ip)
        self.assertIsNone(event.user_agent)
        self.assertIsNone(event.client_correlation_id)

    def test_an_ipv6_address_is_stored(self):
        event = call(actor=self.teacher, request=request(REMOTE_ADDR="2001:db8::7"))
        self.assertEqual(event.source_ip, "2001:db8::7")

    def test_a_very_long_browser_string_is_cut_to_the_column_size(self):
        event = call(actor=self.teacher, request=request(HTTP_USER_AGENT="A" * 2000))
        self.assertEqual(len(event.user_agent), 512)

    def test_the_address_is_the_one_the_edge_proxy_saw_not_the_one_the_client_claims(
        self,
    ):
        """The same rule the rate limiter uses (NUM_PROXIES): a client that
        sends its own X-Forwarded-For cannot choose the address that ends up in
        the audit trail."""
        forged = request(
            REMOTE_ADDR="10.0.0.1",
            HTTP_X_FORWARDED_FOR="6.6.6.6, 203.0.113.5",
        )
        drf = {**settings.REST_FRAMEWORK, "NUM_PROXIES": 1}
        with override_settings(REST_FRAMEWORK=drf):
            event = call(actor=self.teacher, request=forged)
        self.assertEqual(event.source_ip, "203.0.113.5")

    def test_a_nul_byte_in_the_browser_string_is_removed_so_the_event_still_saves(self):
        """Postgres refuses NUL in text; that would silently lose the event."""
        event = call(actor=self.teacher, request=request(HTTP_USER_AGENT="Bro\x00wser"))
        self.assertEqual(event.user_agent, "Browser")

    def test_an_empty_browser_string_is_stored_as_null(self):
        event = call(actor=self.teacher, request=request(HTTP_USER_AGENT=""))
        self.assertIsNone(event.user_agent)

    def test_the_inbound_request_id_is_kept_as_untrusted_context(self):
        event = call(actor=self.teacher, request=request(HTTP_X_REQUEST_ID="abc-123"))
        self.assertEqual(event.client_correlation_id, "abc-123")

    def test_the_id_the_middleware_attached_is_used_when_present(self):
        req = request()
        req.request_id = "from-middleware"
        self.assertEqual(
            call(actor=self.teacher, request=req).client_correlation_id,
            "from-middleware",
        )

    def test_an_unusable_client_id_is_dropped_not_stored(self):
        for bad in ("has space", "x" * 65, "line\nbreak", "trailing\n", "<script>"):
            with self.subTest(bad=bad):
                req = request()
                req.request_id = bad
                self.assertIsNone(
                    call(actor=self.teacher, request=req).client_correlation_id
                )


class TraceIdTest(TestCase):
    """X-5: the trace id is the server's, never the client's."""

    def test_every_event_gets_its_own_server_generated_trace_id(self):
        first, second = call(), call()
        self.assertIsInstance(first.trace_id, uuid.UUID)
        self.assertNotEqual(first.trace_id, second.trace_id)

    def test_a_client_cannot_choose_the_trace_id_by_sending_one(self):
        """Sending another action's trace id as X-Request-ID must not make this
        event part of that action's trail."""
        victim = call()
        forged = request(HTTP_X_REQUEST_ID=victim.trace_id.hex)
        event = call(request=forged)
        self.assertNotEqual(event.trace_id, victim.trace_id)
        self.assertEqual(event.client_correlation_id, victim.trace_id.hex)

    def test_events_inside_one_trace_context_share_its_id(self):
        with trace_context() as trace_id:
            self.assertEqual(current_trace_id(), trace_id)
            first, second = call(), call()
        self.assertEqual(first.trace_id, trace_id)
        self.assertEqual(second.trace_id, trace_id)
        self.assertIsNone(current_trace_id())
        self.assertNotEqual(call().trace_id, trace_id)

    def test_a_server_supplied_id_is_used_for_a_worker_joining_a_trace(self):
        known = uuid.uuid4()
        with trace_context(known):
            self.assertEqual(call().trace_id, known)
        with trace_context(str(known)):
            self.assertEqual(call().trace_id, known)

    def test_a_garbage_trace_id_is_replaced_rather_than_failing_the_request(self):
        with trace_context("not-a-uuid") as trace_id:
            self.assertIsInstance(trace_id, uuid.UUID)
            self.assertEqual(call().trace_id, trace_id)

    def test_trace_contexts_nest_and_restore(self):
        with trace_context() as outer:
            with trace_context() as inner:
                self.assertNotEqual(outer, inner)
                self.assertEqual(call().trace_id, inner)
            self.assertEqual(call().trace_id, outer)

    def test_outside_any_trace_context_the_requests_own_id_is_used(self):
        """FR-A-03 / NFR-OBS-01: with no explicit trace_context() open, the
        emitter must still land on the SAME id AutoGrader.request_context
        already carries across this request and its Celery tasks - not a
        disconnected random id - so one id reconstructs the whole action."""
        known = uuid.uuid4()
        token = set_request_id(known.hex)
        try:
            self.assertIsNone(current_trace_id())  # no explicit context open
            self.assertEqual(call().trace_id, known)
        finally:
            reset_request_id(token)

    def test_an_explicit_trace_context_still_wins_over_the_requests_own_id(self):
        token = set_request_id(uuid.uuid4().hex)
        try:
            with trace_context() as joined:
                self.assertEqual(call().trace_id, joined)
        finally:
            reset_request_id(token)

    def test_a_non_uuid_shaped_request_id_is_replaced_not_used(self):
        """An inbound X-Request-ID is accepted on a broader charset than a
        UUID for logging (is_valid_request_id) - it must never be assumed to
        be one here just because request_context accepted it."""
        token = set_request_id("not-a-uuid-but-valid-for-logging")
        try:
            event = call()
            self.assertIsInstance(event.trace_id, uuid.UUID)
            self.assertNotEqual(str(event.trace_id), "not-a-uuid-but-valid-for-logging")
        finally:
            reset_request_id(token)

    def test_with_no_request_context_and_no_explicit_trace_a_fresh_id_is_minted(self):
        self.assertIsNone(get_request_id())
        self.assertIsNone(current_trace_id())
        self.assertIsInstance(call().trace_id, uuid.UUID)


class RetentionClassTest(TestCase):
    def test_an_ordinary_action_is_general(self):
        self.assertEqual(call().retention_class, RetentionClass.GENERAL)

    def test_the_actions_that_always_touch_student_records_are_kept_three_years(self):
        self.assertTrue(STUDENT_RECORD_ACTIONS)
        for action in STUDENT_RECORD_ACTIONS:
            with self.subTest(action=action):
                event = emit(action, actor=None, target_type="Submission")
                self.assertEqual(event.retention_class, RetentionClass.STUDENT_RECORD)

    def test_any_action_can_be_raised_to_student_record(self):
        event = call(touches_student_record=True)
        self.assertEqual(event.retention_class, RetentionClass.STUDENT_RECORD)

    def test_a_caller_cannot_lower_an_actions_retention(self):
        event = emit(
            AuditAction.SUBMISSION_UPLOAD,
            actor=None,
            target_type="Submission",
            touches_student_record=False,
        )
        self.assertEqual(event.retention_class, RetentionClass.STUDENT_RECORD)

    def test_there_is_no_way_to_choose_a_retention_class_directly(self):
        with self.assertRaises(TypeError):
            call(retention_class=RetentionClass.GENERAL)


class RejectedWritesTest(TestCase):
    """FR-A-02: a write missing a required field is rejected, not stored."""

    def rejected(self, **over):
        before = AuditEvent.objects.count()
        result = call(**over)
        self.assertIsNone(result)
        self.assertEqual(AuditEvent.objects.count(), before)

    def test_an_unknown_action_is_rejected(self):
        before = AuditEvent.objects.count()
        self.assertIsNone(emit("MADE_UP_ACTION", actor=None, target_type="Assignment"))
        self.assertEqual(AuditEvent.objects.count(), before)

    def test_an_action_may_be_given_as_its_string_value(self):
        event = emit("ASSIGNMENT_COPY", actor=None, target_type="Assignment")
        self.assertEqual(event.action, "ASSIGNMENT_COPY")

    def test_a_missing_or_malformed_target_type_is_rejected(self):
        for bad in (None, "", "has space", "x" * 65, 5):
            with self.subTest(target_type=bad):
                self.rejected(target_type=bad)

    def test_a_target_id_that_is_not_a_uuid_is_rejected(self):
        self.rejected(target_id="12345")

    def test_an_unknown_outcome_is_rejected(self):
        self.rejected(outcome="MAYBE")

    def test_a_failure_without_an_error_class_is_rejected(self):
        for outcome in (AuditOutcome.FAILURE, AuditOutcome.DENIED):
            with self.subTest(outcome=outcome):
                self.rejected(outcome=outcome, error_class=None)

    def test_a_success_with_an_error_class_is_rejected(self):
        self.rejected(outcome=AuditOutcome.SUCCESS, error_class=ErrorClass.USER)

    def test_an_unknown_error_class_is_rejected(self):
        self.rejected(outcome=AuditOutcome.FAILURE, error_class="OOPS")

    def test_a_malformed_reason_code_is_rejected(self):
        for bad in ("lowercase", "HAS SPACE", "X" * 65, ""):
            with self.subTest(reason_code=bad):
                self.rejected(reason_code=bad)

    def test_a_licence_or_department_that_is_not_a_uuid_is_rejected(self):
        self.rejected(school_id="nope")
        self.rejected(department_id="nope")

    def test_a_user_of_an_unknown_type_is_rejected(self):
        odd = mock.Mock(
            id=uuid.uuid4(), user_type="ALIEN", email="a@b.c", school_id=None
        )
        self.rejected(actor=odd)

    def test_strict_mode_raises_so_a_call_site_test_can_see_the_mistake(self):
        with self.assertRaises(AuditValidationError):
            call(outcome="MAYBE", strict=True)
        with self.assertRaises(AuditValidationError):
            emit("MADE_UP", actor=None, target_type="Assignment", strict=True)
        self.assertEqual(AuditEvent.objects.count(), 0)

    def test_a_rejection_is_reported_in_the_operational_log_without_the_values(self):
        with self.assertLogs("audit.emitter", level="ERROR") as logs:
            call(outcome="MAYBE")
        text = "\n".join(logs.output)
        self.assertIn("rejected", text)
        self.assertIn("ASSIGNMENT_COPY", text)
        self.assertNotIn("MAYBE", text)

    def test_odd_input_never_raises_to_the_caller(self):
        for over in (
            {"metadata": "not a dict"},
            {"metadata": ["a"]},
            {"before": 5},
            {"request": object()},
            {"actor": object()},
            {"target_type": object()},
            {"school_id": object()},
        ):
            with self.subTest(over=over):
                call(**over)  # must not raise


class MetadataAtTheEmitterTest(TestCase):
    def test_a_key_valid_globally_but_wrong_for_this_action_is_dropped_at_emit(self):
        """03a_data_model.md 2.1: the allow-list is PER ACTION. `credits` is a
        real key in the shared pool (CREDIT_TRANSACTION carries it) but is not
        on ASSIGNMENT_COPY's (call()'s default action) own list - `emit()`
        itself must apply that narrowing, not just the pure function in
        isolation."""
        self.assertIn("credits", ALLOWED_KEYS)
        self.assertNotIn("credits", metadata_allowlist_for(AuditAction.ASSIGNMENT_COPY))
        event = call(metadata={"credits": 5})
        self.assertEqual(event.metadata, {})

    def test_an_unknown_metadata_key_is_dropped_but_the_event_is_still_written(self):
        # A key from ASSIGNMENT_COPY's own allow-list (call()'s default
        # action) - it must survive, unlike a key that is not even in the
        # shared pool at all (see the per-action tests in tests_metadata.py
        # for a key that is in ALLOWED_KEYS but not this action's own list).
        key = sorted(metadata_allowlist_for(AuditAction.ASSIGNMENT_COPY))[0]
        with self.assertLogs("audit.emitter", level="ERROR") as logs:
            event = call(metadata={key: 1, "student_name": "Ada Lovelace"})
        self.assertEqual(event.metadata, {key: 1})
        text = "\n".join(logs.output)
        self.assertIn("student_name", text)
        self.assertNotIn("Ada Lovelace", text)

    def test_before_and_after_follow_the_same_allow_list(self):
        key = sorted(ALLOWED_KEYS)[0]
        event = call(
            before={key: 1, "answer_text": "the mitochondria"},
            after={key: 2, "answer_text": "the powerhouse"},
        )
        self.assertEqual(event.before, {key: 1})
        self.assertEqual(event.after, {key: 2})

    def test_metadata_defaults_to_an_empty_object(self):
        self.assertEqual(call().metadata, {})

    def test_a_nul_byte_in_a_value_is_dropped_so_the_event_still_saves(self):
        """Postgres jsonb refuses \\u0000; without this the whole event is lost."""
        key = sorted(ALLOWED_KEYS)[0]
        with self.assertLogs("audit.emitter", level="ERROR"):
            event = call(metadata={key: "a\x00b"})
        self.assertIsNotNone(event)
        self.assertEqual(event.metadata, {})


class LoggingNeverFailsTheUserActionTest(TestCase):
    """FR-A-11. The audit store is broken; the action carries on."""

    def break_the_table(self):
        with connection.cursor() as cursor:
            cursor.execute("ALTER TABLE audit_auditevent RENAME TO audit_auditevent_x")

    def test_a_broken_audit_table_does_not_raise_and_returns_nothing(self):
        self.break_the_table()
        with self.assertLogs("audit.emitter", level="ERROR"):
            self.assertIsNone(call())

    def test_the_callers_transaction_is_still_usable_after_the_store_fails(self):
        """A failed INSERT poisons a Postgres transaction unless it ran in its
        own savepoint. The rest of the user's action must still be able to save."""
        self.break_the_table()
        with transaction.atomic():
            work_before = CustomUser.objects.count()
            with self.assertLogs("audit.emitter", level="ERROR"):
                self.assertIsNone(call())
            make_user("still.works@example.org")
            self.assertEqual(CustomUser.objects.count(), work_before + 1)

    def test_strict_mode_never_raises_for_a_store_failure(self):
        self.break_the_table()
        with self.assertLogs("audit.emitter", level="ERROR"):
            self.assertIsNone(call(strict=True))

    def test_the_failure_report_never_carries_values_from_the_error_text(self):
        """Database errors quote the failing row, which includes the email."""
        leaky = IntegrityError("Failing row contains (secret.teacher@example.edu)")
        teacher = make_user("secret.teacher@example.edu")
        with mock.patch.object(AuditEvent.objects, "create", side_effect=leaky):
            with self.assertLogs("audit.emitter", level="ERROR") as logs:
                self.assertIsNone(call(actor=teacher))
        text = "\n".join(logs.output) + repr([r.__dict__ for r in logs.records])
        self.assertNotIn("secret.teacher", text)
        self.assertIn("IntegrityError", text)
        self.assertIn("ASSIGNMENT_COPY", text)

    def test_any_exception_type_from_the_store_is_contained(self):
        for exc in (DatabaseError("x"), RuntimeError("x"), KeyError("x"), OSError("x")):
            with self.subTest(exc=type(exc).__name__):
                with mock.patch.object(AuditEvent.objects, "create", side_effect=exc):
                    with self.assertLogs("audit.emitter", level="ERROR"):
                        self.assertIsNone(call())


class DatabaseUnreachableTest(TransactionTestCase):
    """The harder case: not a broken table but no database at all."""

    def test_an_unreachable_database_does_not_raise(self):
        settings_dict = connection.settings_dict
        original_port = settings_dict["PORT"]
        original_timeout = settings_dict["OPTIONS"].get("connect_timeout")
        connection.close()
        settings_dict["PORT"] = "1"  # nothing listens here
        settings_dict["OPTIONS"]["connect_timeout"] = 2
        try:
            with self.assertLogs("audit.emitter", level="ERROR"):
                self.assertIsNone(call())
        finally:
            settings_dict["PORT"] = original_port
            if original_timeout is None:
                settings_dict["OPTIONS"].pop("connect_timeout", None)
            else:
                settings_dict["OPTIONS"]["connect_timeout"] = original_timeout
            connection.close()
        self.assertEqual(AuditEvent.objects.count(), 0)
        self.assertIsNotNone(call())


class OperationalLogTest(TestCase):
    def test_a_successful_emit_logs_nothing_at_error_level(self):
        with self.assertNoLogs("audit.emitter", level=logging.ERROR):
            call()
