# Generated by Django 5.2.6 on 2025-10-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="activation_expires",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Activation Expires"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="activation_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=64,
                null=True,
                verbose_name="Activation Token",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether this user should be "
                "treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
