# Generated by Django 5.2.6 on 2025-09-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
