# Generated by Django 5.2.6 on 2025-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_email_verified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passwordresetotp",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
    ]
