# Generated by Django 5.2.6 on 2025-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_passwordchangeotp"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordchangeotp",
            name="hash_value",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="hash_value",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="passwordchangeotp",
            name="code",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
    ]
