# Generated by Django 5.2.6 on 2025-10-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_passwordchangeotp_hash_value_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passwordchangeotp",
            name="hash_value",
        ),
        migrations.RemoveField(
            model_name="passwordresetotp",
            name="hash_value",
        ),
        migrations.AddConstraint(
            model_name="passwordchangeotp",
            constraint=models.UniqueConstraint(
                fields=("user", "code"),
                name="password_change_unique_user_code_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="passwordresetotp",
            constraint=models.UniqueConstraint(
                fields=("user", "code"), name="password_reset_unique_user_code_per_user"
            ),
        ),
    ]
