# Generated by Django 5.2.6 on 2025-12-23 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0009_school"),
        ("users", "0009_remove_passwordchangeotp_hash_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="classrooms.school",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("SCHOOL_ADMIN", "School Admin"),
                    ("SUPER_ADMIN", "Super Admin"),
                ],
                default="TEACHER",
                max_length=20,
            ),
        ),
    ]
