# Generated by Django 5.2.6 on 2026-01-26 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_concurrentusersnapshot_useractivity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concurrentusersnapshot",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
