# Generated by Django 5.2.6 on 2026-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_concurrentusersnapshot_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
