# Generated by Django 5.2.6 on 2026-03-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_customuser_middle_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
