# Generated by Django 5.2.6 on 2026-03-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_customuser_bio_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.DeleteModel(
            name="Settings",
        ),
    ]
