# Generated by Django 5.2.6 on 2026-03-23 22:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_remove_customuser_bio_delete_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("LIGHT", "Light"),
                            ("DARK", "Dark"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=20,
                    ),
                ),
                ("notify_student_submission", models.BooleanField(default=False)),
                ("notify_weekly_summary", models.BooleanField(default=False)),
                ("notify_assignment_due_reminder", models.BooleanField(default=False)),
                ("notify_grading_complete", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
