# Generated by Django 5.2.6 on 2026-04-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_betawhitelist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Waitlist",
            },
        ),
        migrations.AddField(
            model_name="betawhitelist",
            name="mode",
            field=models.CharField(
                choices=[("BETA", "Beta"), ("WAITLIST", "Waitlist")],
                default="BETA",
                max_length=20,
            ),
        ),
    ]
