# Generated by Django 5.2.6 on 2026-04-20 12:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_waitlist_betawhitelist_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="betawhitelist",
            name="test_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="betawhitelist",
            name="id",
            field=models.CharField(
                max_length=100, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
