# Generated by Django 5.2.6 on 2026-04-20 12:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_betawhitelist_test_id_alter_betawhitelist_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betawhitelist",
            name="test_id",
        ),
        migrations.AlterField(
            model_name="betawhitelist",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
