# Generated by Django 5.2.6 on 2026-04-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_remove_betawhitelist_test_id_alter_betawhitelist_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitlist",
            name="id",
        ),
        migrations.AddField(
            model_name="waitlist",
            name="test_id",
            field=models.CharField(
                default="", max_length=100, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
