# Generated by Django 5.2.6 on 2026-04-20 12:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_remove_waitlist_id_waitlist_test_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="waitlist",
            name="test_id",
        ),
        migrations.AddField(
            model_name="waitlist",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
