# Generated by Django 5.2.6 on 2026-04-20 15:50

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_remove_waitlist_test_id_waitlist_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.get_user_name
            ),
        ),
    ]
