# Generated by Django 5.2.6 on 2026-05-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="registration_method",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("GOOGLE", "Google"),
                    ("FACEBOOK", "Facebook"),
                    ("TWITTER", "Twitter"),
                ],
                default="EMAIL",
                max_length=20,
            ),
        ),
    ]
