# Generated by Django 5.2.6 on 2026-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_customuser_registration_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
