# Generated by Django 5.2.6 on 2026-05-23 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_customuser_profile_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="middle_name",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
