# Generated by Django 5.2.6 on 2026-05-28 10:39

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_usergooglecredentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergooglecredentials",
            name="access_token",
            field=encrypted_model_fields.fields.EncryptedCharField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usergooglecredentials",
            name="refresh_token",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
