# Generated by Django 5.2.6 on 2026-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_settings_notify_new_assignment_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="notify_assignment_due_reminder",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="notify_grading_complete",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="notify_new_assignment_posted",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="notify_student_submission",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="settings",
            name="notify_weekly_summary",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
