# Generated by Django 5.2.6 on 2026-07-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0032_alter_settings_notify_assignment_due_reminder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="notify_at_risk_student_alerts",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="settings",
            name="notify_teacher_activity_alerts",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
