# Generated by Django 5.2.6 on 2026-08-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_settings_notify_at_risk_student_alerts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passwordresetotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="passwordresetotp",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
