# Generated by Django 5.2.6 on 2026-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_passwordresetotp_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="notify_assignment_edited",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
