# Generated by Django 5.2.6 on 2026-09-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_settings_notify_assignment_edited"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
