# Generated by Django 5.2.6 on 2026-09-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0036_customuser_failed_login_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="True for an account whose current password was generated by the system (e.g. a school-license teacher invite) rather than chosen by the user. While True, the API rejects every request except change-password and logout.",
            ),
        ),
    ]
