# Generated by Django 5.2.6 on 2026-09-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_customuser_must_change_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False,
                help_text="True for an account whose current password was generated by the system (e.g. a school-license teacher invite) rather than chosen by the user. Not enforced server-side - the frontend reads this (see CustomUserSerializer) to show a nudge to change it.",
            ),
        ),
    ]
