# Generated by Django 5.2.6 on 2026-09-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0038_alter_customuser_must_change_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="token_epoch",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
