# Generated by Django 5.2.6 on 2026-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_customuser_token_epoch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveSmallIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="True for an account whose current password was generated by the system (e.g. a school-license teacher invite) rather than chosen by the user. Not enforced server-side - the frontend reads this (see CustomUserSerializer) to show a nudge to change it.",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="token_epoch",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
