# Generated by Django 5.2.6 on 2026-02-27 10:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("PRO", "Pro"),
                            ("POWER", "Power"),
                        ],
                        help_text="Unique code for the plan",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the plan",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "monthly_credits",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of credits granted each month"
                    ),
                ),
                (
                    "carry_over_percent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage of unused credits to carry over to the next month",
                        max_digits=5,
                    ),
                ),
                (
                    "carry_over_max",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Maximum number of credits that can be carried over to the next month",
                    ),
                ),
                (
                    "carry_over_expiry_months",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of months credits can be carried over",
                    ),
                ),
                (
                    "overage_block_size",
                    models.PositiveBigIntegerField(
                        default=0,
                        help_text="Number of credits to add when overage is detected",
                    ),
                ),
                (
                    "overage_block_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Price of each overage block",
                        max_digits=10,
                    ),
                ),
                (
                    "max_overage_blocks",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Maximum number of overage blocks to add"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the plan is active"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditBucket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "bucket_type",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("CARRY_OVER", "Carry Over"),
                            ("OVERAGE", "Overage"),
                        ],
                        help_text="Type of credit bucket",
                        max_length=20,
                    ),
                ),
                (
                    "total_credits",
                    models.PositiveIntegerField(
                        default=0, help_text="Total credits in the bucket"
                    ),
                ),
                (
                    "remaining_credits",
                    models.PositiveIntegerField(
                        default=0, help_text="Remaining credits in the bucket"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the credits expire",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the credit bucket was created",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns the credit bucket",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_buckets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ledger_type",
                    models.CharField(
                        choices=[
                            ("CONSUME", "Consume"),
                            ("REFUND", "Refund"),
                            ("GRANT", "Grant"),
                            ("EXPIRE", "Expire"),
                            ("PURCHASE", "Purchase"),
                        ],
                        help_text="Type of credit ledger",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Amount of credits to be added or "
                        "subtracted from the bucket, positive for additions, negative for subtractions"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference for the credit ledger",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Metadata for the credit ledger",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the credit ledger was created",
                    ),
                ),
                (
                    "bucket",
                    models.ForeignKey(
                        help_text="Credit bucket the ledger is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_ledgers",
                        to="billing.creditbucket",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns the credit ledger",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledgers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the subscription is active"
                    ),
                ),
                (
                    "billing_cycle_start",
                    models.DateTimeField(
                        help_text="Start date of the current billing cycle"
                    ),
                ),
                (
                    "billing_cycle_end",
                    models.DateTimeField(
                        help_text="End date of the current billing cycle"
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True, help_text="Whether the subscription auto-renews"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the subscription was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the subscription was last updated",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Plan the user is subscribed to",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns the subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="creditbucket",
            index=models.Index(
                fields=["user", "bucket_type", "expires_at"],
                name="billing_cre_user_id_d362ae_idx",
            ),
        ),
    ]
