# Generated by Django 5.2.6 on 2026-02-27 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="usersubscription",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="carry_over_max",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum number of credits that can be carried over to the next month",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="overage_block_size",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of credits to add when overage is detected"
            ),
        ),
        migrations.AddConstraint(
            model_name="usersubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user",),
                name="one_active_subscription_per_user",
            ),
        ),
    ]
