# Generated by Django 5.2.6 on 2026-02-27 19:00

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_alter_subscriptionplan_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Amount of credits consumed from the bucket"
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        help_text="Feature or service for which credits are being consumed",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of task being performed",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the task",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the credit usage log was created",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditWallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overage_blocks_used",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of overage blocks used in the current billing cycle",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the credit wallet was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the credit wallet was last updated",
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="creditbucket",
            name="billing_cre_user_id_d362ae_idx",
        ),
        migrations.RemoveField(
            model_name="creditbucket",
            name="remaining_credits",
        ),
        migrations.RemoveField(
            model_name="creditbucket",
            name="user",
        ),
        migrations.AddField(
            model_name="creditbucket",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the credit bucket was last updated",
            ),
        ),
        migrations.AddField(
            model_name="creditbucket",
            name="used_credits",
            field=models.PositiveIntegerField(
                default=0, help_text="Credits consumed from this bucket"
            ),
        ),
        migrations.AlterField(
            model_name="creditbucket",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the credits expire. Only for carry_over / overage",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creditusagelog",
            name="bucket",
            field=models.ForeignKey(
                help_text="Credit bucket the usage log is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_usage_logs",
                to="billing.creditbucket",
            ),
        ),
        migrations.AddField(
            model_name="creditwallet",
            name="user",
            field=models.OneToOneField(
                help_text="User who owns the credit wallet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_wallet",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="creditusagelog",
            name="wallet",
            field=models.ForeignKey(
                help_text="Credit wallet the usage log is associated with",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credit_usage_logs",
                to="billing.creditwallet",
            ),
        ),
        migrations.AddField(
            model_name="creditbucket",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                help_text="Wallet that owns the credit bucket",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buckets",
                to="billing.creditwallet",
            ),
        ),
        migrations.AddIndex(
            model_name="creditbucket",
            index=models.Index(
                fields=["wallet", "bucket_type", "expires_at"],
                name="billing_cre_wallet__712810_idx",
            ),
        ),
    ]
