# Generated by Django 5.2.6 on 2026-02-28 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_creditusagelog_creditwallet_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditwallet",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="creditbucket",
            name="wallet",
            field=models.ForeignKey(
                help_text="Wallet that owns the credit bucket",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buckets",
                to="billing.creditwallet",
            ),
        ),
    ]
