# Generated by Django 5.2.6 on 2026-03-02 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_alter_creditwallet_options_alter_creditbucket_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="pending_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_pending_subscriptions",
                to="billing.subscriptionplan",
            ),
        ),
    ]
