# Generated by Django 5.2.6 on 2026-03-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_usersubscription_pending_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PRO", "Pro"),
                    ("POWER", "Power"),
                    ("BETA", "Beta"),
                ],
                help_text="Unique code for the plan",
                max_length=20,
                unique=True,
            ),
        ),
    ]
