# Generated by Django 5.2.6 on 2026-03-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_alter_subscriptionplan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditbucket",
            name="is_processed",
            field=models.BooleanField(
                default=False,
                help_text="True if the bucket has been handled by the expiry cleanup task",
            ),
        ),
        migrations.AddField(
            model_name="creditusagelog",
            name="is_refunded",
            field=models.BooleanField(
                default=False, help_text="Whether the credit was refunded"
            ),
        ),
    ]
