# Generated by Django 5.2.6 on 2026-03-11 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_creditbucket_is_processed_creditusagelog_is_refunded"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BetaProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_beta_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("first_ai_action_at", models.DateTimeField(blank=True, null=True)),
                ("last_active_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_date", models.DateField(blank=True, null=True)),
                ("initial_beta_credits", models.PositiveIntegerField(default=10000000)),
                (
                    "total_credits_used",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("credits_used_grading", models.PositiveIntegerField(default=0)),
                ("credits_used_creation", models.PositiveIntegerField(default=0)),
                ("analytics_view_count", models.PositiveIntegerField(default=0)),
                ("distinct_login_days", models.PositiveSmallIntegerField(default=0)),
                ("has_hit_80_percent", models.BooleanField(default=False)),
                ("has_hit_cap", models.BooleanField(default=False)),
                (
                    "conversion_probability",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "days_to_first_action",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("usage_velocity", models.FloatField(db_index=True, default=0.0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beta_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Beta Usage Profile",
                "ordering": ["-conversion_probability"],
                "indexes": [
                    models.Index(
                        fields=["conversion_probability"],
                        name="billing_bet_convers_c9d3e7_idx",
                    ),
                    models.Index(
                        fields=["last_active_at"], name="billing_bet_last_ac_8e7a14_idx"
                    ),
                    models.Index(
                        fields=["joined_beta_at"], name="billing_bet_joined__ca52a2_idx"
                    ),
                ],
            },
        ),
    ]
