# Generated by Django 5.2.6 on 2026-05-07 16:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0008_betaprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="betaprofile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="betaprofile",
            name="initial_beta_credits",
            field=models.PositiveIntegerField(default=20000000),
        ),
        migrations.AlterField(
            model_name="creditbucket",
            name="bucket_type",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("CARRY_OVER", "Carry Over"),
                    ("OVERAGE", "Overage"),
                    ("MANUAL_GRANT", "Manual Grant"),
                ],
                help_text="Type of credit bucket",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditbucket",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text=(
                    "Date and time when the credits expire. Only for carry_over / overage",
                    "Null means the credits never expire (valid for MANUAL_GRANT).",
                ),
                null=True,
            ),
        ),
    ]
