# Generated by Django 5.2.6 on 2026-05-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_betaprofile_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="betaprofile",
            name="id",
            field=models.CharField(
                default="00000000-0000-0000-0000-000000000000",
                max_length=100,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
