# Generated by Django 5.2.6 on 2026-05-07 16:36

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_alter_betaprofile_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betaprofile",
            name="uuid",
        ),
        migrations.AddField(
            model_name="betaprofile",
            name="uid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="betaprofile",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
