# Generated by Django 5.2.6 on 2026-05-07 16:41
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    BetaProfile = apps.get_model("billing", "BetaProfile")
    for row in BetaProfile.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=["uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0011_remove_betaprofile_uuid_betaprofile_uid_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
