# Generated by Django 5.2.6 on 2026-05-07 16:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0012_populate_beta_profile_uuids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="betaprofile",
            name="id",
        ),
        migrations.AlterField(
            model_name="betaprofile",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
