# Generated by Django 5.2.6 on 2026-05-07 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0013_remove_betaprofile_id_alter_betaprofile_uid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="betaprofile",
            old_name="uid",
            new_name="id",
        ),
    ]
