# Generated by Django 5.2.6 on 2026-05-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_rename_uid_betaprofile_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="betaprofile",
            name="credits_used_feedback",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
