# Generated by Django 5.2.6 on 2026-06-04 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0015_betaprofile_credits_used_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("ADVANCED_COURSE_ANALYTICS", "Advanced Course Analytics"),
                            (
                                "ADVANCED_ASSIGNMENT_ANALYTICS",
                                "Advanced Assignment Analytics",
                            ),
                            (
                                "AI_PROMPT_ASSIGNMENT_CREATION",
                                "AI Prompt-Based Assignment Creation",
                            ),
                            (
                                "AI_PROMPT_ANALYTICS_SUMMARY",
                                "AI Prompt-Based Analytics Summarization",
                            ),
                            ("PRE_SCHEDULED_GRADING", "Pre-Scheduled Grading"),
                            (
                                "ADVANCED_STUDENT_ANALYTICS",
                                "Advanced Student Analytics/Insights",
                            ),
                            (
                                "AI_EMAIL_FEEDBACK",
                                "Optional AI Email Feedback for Assignments",
                            ),
                            ("CREDIT_ROLLOVER_25", "25% AI Credit Rollover"),
                            ("UNLIMITED_COURSES", "Unlimited Courses (Archivable)"),
                            ("INVITE_STUDENTS_UPLOAD", "Invite Students to Upload"),
                            ("BATCH_GRADING", "Batch Grading/Uploading"),
                            ("BASIC_INSIGHTS", "Basic Course/Insights"),
                            ("ADMIN_MANAGED_BILLING", "Admin-Managed Billing"),
                            ("SHARED_CREDIT_POOL", "Shared Credit Pool"),
                            ("DEDICATED_SUPPORT", "Dedicated Support"),
                        ],
                        max_length=60,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable label shown on the pricing page",
                        max_length=200,
                    ),
                ),
                (
                    "is_gating_feature",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "True = used in code to gate access to a feature. "
                            "False = display-only catalogue label."
                        ),
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.AlterModelOptions(
            name="subscriptionplan",
            options={"ordering": ["category", "tier"]},
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="overage_block_price",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="category",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual"), ("LICENSE", "License")],
                default="INDIVIDUAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="highlight",
            field=models.CharField(
                blank=True,
                choices=[("BEST_VALUE", "Best Value"), ("GREAT_VALUE", "Great Value")],
                help_text="Optional badge shown on the plan card (BEST_VALUE or GREAT_VALUE)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="interval",
            field=models.CharField(
                choices=[("MONTHLY", "Monthly"), ("ANNUAL", "Annual")],
                default="MONTHLY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_contact_sales",
            field=models.BooleanField(
                default=False,
                help_text="If true, frontend shows 'Contact sales' instead of a checkout CTA",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="overage_credit_price_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Price per overage block in USD cents (e.g. 400 = $4.00)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="price_cents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Monthly or annual price in USD cents (e.g. 2499 = $24.99)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="product_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Product ID (prod_xxx). Internal reference only.n",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID (price_xxx). Sent to frontend as `price_id`.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="tagline",
            field=models.CharField(
                blank=True, help_text="Short phrase describing the plan", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PRO", "Pro"),
                    ("POWER", "Power"),
                    ("BETA", "Beta"),
                    ("CUSTOM", "Custom"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="carry_over_expiry_months",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="How many months carry-over credits remain valid"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="carry_over_max",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum raw credits that can be carried over (display value × 1000)",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="carry_over_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentage of unused credits to carry over (e.g. 25.00 for 25%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="max_overage_blocks",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Maximum overage blocks a user can purchase per cycle",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="monthly_credits",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Raw credits granted per cycle (display value × 1000). Null for Custom/contact-sales plans.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="overage_block_size",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Raw credits per overage block (display value × 1000, e.g. 5_000_000 = 5K)",
            ),
        ),
        migrations.CreateModel(
            name="PlanFeatureInclusion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "included",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this feature is available on this plan",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Controls render order on the pricing page card",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_inclusions",
                        to="billing.planfeature",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feature_inclusions",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "display_order"],
                "unique_together": {("plan", "feature")},
            },
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.ManyToManyField(
                related_name="plans",
                through="billing.PlanFeatureInclusion",
                to="billing.planfeature",
            ),
        ),
    ]
