# Generated by Django 5.2.6 on 2026-06-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0016_planfeature_alter_subscriptionplan_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="overage_credit_price_cents",
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="overage_block_size",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Price per overage block in USD cents (e.g. 400 = $4.00)",
            ),
        ),
    ]
