# Generated by Django 5.2.6 on 2026-06-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0017_remove_subscriptionplan_overage_credit_price_cents_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="overage_block_price",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Price per overage block in USD cents (e.g. 400 = $4.00)",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="overage_block_size",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Raw credits per overage block (display value × 1000, e.g. 5_000_000 = 5K)",
            ),
        ),
    ]
