# Generated by Django 5.2.6 on 2026-06-09 10:01

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0018_subscriptionplan_overage_block_price_and_more"),
        ("classrooms", "0013_studentcourse_ai_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "billing_cycle_start",
                    models.DateTimeField(
                        help_text="Start date of the current billing cycle"
                    ),
                ),
                (
                    "billing_cycle_end",
                    models.DateTimeField(
                        help_text="End date of the current billing cycle"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the license subscription is active",
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the license auto-renews at cycle end",
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        help_text="Stripe subscription ID for this license (one per school)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the license was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the license was last updated",
                    ),
                ),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="Admin user who manages this license (typically school admin)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="managed_license_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="License plan (must have category=LICENSE)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_subscriptions",
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        help_text="School that owns this license",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license_subscriptions",
                        to="classrooms.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "License Subscription",
                "verbose_name_plural": "License Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SchoolCreditAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "monthly_allocation",
                    models.PositiveIntegerField(
                        help_text="Raw monthly credit allocation for this teacher (display value × 1000)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this teacher is actively enrolled under the license",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the allocation was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the allocation was last updated",
                    ),
                ),
                (
                    "license_subscription",
                    models.ForeignKey(
                        help_text="License subscription this allocation belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="billing.licensesubscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Teacher enrolled under this license",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="school_credit_allocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "School Credit Allocation",
                "verbose_name_plural": "School Credit Allocations",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["license_subscription", "is_active"],
                        name="billing_sch_license_bbc048_idx",
                    ),
                    models.Index(
                        fields=["user", "is_active"],
                        name="billing_sch_user_id_866a62_idx",
                    ),
                ],
                "unique_together": {("license_subscription", "user")},
            },
        ),
    ]
