# Generated by Django 5.2.6 on 2026-06-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0019_licensesubscription_schoolcreditallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesubscription",
            name="contract_months",
            field=models.PositiveSmallIntegerField(
                choices=[(9, "9 Months"), (10, "10 Months"), (12, "12 Months")],
                default=12,
                help_text="Contract duration in months. Schools can choose 9, 10, or 12 month billing periods. This determines how far ahead billing_cycle_end is set on creation and each renewal.",
            ),
        ),
        migrations.AddField(
            model_name="licensesubscription",
            name="max_seats",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Maximum number of teacher seats allowed under this license. 0 = unlimited (e.g. for Custom contracts). Enforced on enrollment.",
            ),
        ),
    ]
