# Generated by Django 5.2.6 on 2026-06-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0020_licensesubscription_contract_months_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditbucket",
            name="bucket_type",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("CARRY_OVER", "Carry Over"),
                    ("OVERAGE", "Overage"),
                    ("MANUAL_GRANT", "Manual Grant"),
                    ("TRIAL", "Trial"),
                ],
                help_text="Type of credit bucket",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditledger",
            name="ledger_type",
            field=models.CharField(
                choices=[
                    ("CONSUME", "Consume"),
                    ("REFUND", "Refund"),
                    ("GRANT", "Grant"),
                    ("EXPIRE", "Expire"),
                    ("PURCHASE", "Purchase"),
                    ("PLAN_CHANGE", "Plan Change"),
                ],
                help_text="Type of credit ledger",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="licensesubscription",
            name="contract_months",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 Month"),
                    (9, "9 Months"),
                    (10, "10 Months"),
                    (12, "12 Months"),
                ],
                default=12,
                help_text="Contract duration in months. Schools can choose 9, 10, or 12 month billing periods. This determines how far ahead billing_cycle_end is set on creation and each renewal.",
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PRO", "Pro"),
                    ("POWER", "Power"),
                    ("BETA", "Beta"),
                    ("CUSTOM", "Custom"),
                ],
                help_text="Unique code for the plan",
                max_length=20,
                unique=True,
            ),
        ),
    ]
