# Generated by Django 5.2.6 on 2026-06-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0021_alter_creditbucket_bucket_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="is_trial",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "True while this subscription is in its free trial period ",
                    "Flipped to False on trial expiry or paid conversion",
                ),
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="trial_end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    "Datetime when the free trial expires. Null for non-trial subscriptions. "
                    "Celery checks this field nightly to trigger expiry cleanup"
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="creditbucket",
            name="bucket_type",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("CARRY_OVER", "Carry Over"),
                    ("OVERAGE", "Overage"),
                    ("MANUAL_GRANT", "Manual Grant"),
                    ("TRIAL", "Free Trial"),
                ],
                help_text="Type of credit bucket",
                max_length=20,
            ),
        ),
    ]
