# Generated by Django 5.2.6 on 2026-06-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing",
            "0022_usersubscription_is_trial_usersubscription_trial_end_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PRO", "Pro"),
                    ("POWER", "Power"),
                    ("BETA", "Beta"),
                    ("CUSTOM", "Custom"),
                    ("STANDARD_ANNUAL", "Standard Annual"),
                    ("PRO_ANNUAL", "Pro Annual"),
                    ("POWER_ANNUAL", "Power Annual"),
                ],
                help_text="Unique code for the plan",
                max_length=20,
                unique=True,
            ),
        ),
    ]
