# Generated by Django 5.2.6 on 2026-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0023_alter_subscriptionplan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesubscription",
            name="custom_price_cents",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Negotiated monthly price for this license, overriding the plan's default price. Set by super admin.",
                null=True,
            ),
        ),
    ]
