# Generated by Django 5.2.6 on 2026-06-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0025_alter_subscriptionplan_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesubscription",
            name="total_credits_consumed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total raw credits consumed by all teachers under this license in the current billing cycle. Used for global cap enforcement.",
            ),
        ),
    ]
