# Generated by Django 5.2.6 on 2026-06-18 19:06

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0026_licensesubscription_total_credits_consumed"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_event_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-processed_at"],
            },
        ),
        migrations.AddField(
            model_name="creditwallet",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="licensesubscription",
            name="stripe_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRIALING", "Trialing"),
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past Due"),
                    ("CANCELED", "Canceled"),
                    ("INCOMPLETE", "Incomplete"),
                    ("UNPAID", "Unpaid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TRIALING", "Trialing"),
                    ("ACTIVE", "Active"),
                    ("PAST_DUE", "Past Due"),
                    ("CANCELED", "Canceled"),
                    ("INCOMPLETE", "Incomplete"),
                    ("UNPAID", "Unpaid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
