# Generated by Django 5.2.6 on 2026-06-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0027_stripeevent_creditwallet_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="is_trial",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text=(
                    "True while this subscription is in its free trial period ",
                    "Flipped to False on trial expiry or paid conversion",
                ),
                null=True,
            ),
        ),
    ]
