# Generated by Django 5.2.6 on 2026-06-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0028_alter_usersubscription_is_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="next_credit_grant_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text=(
                    "When the current MONTHLY credit bucket expires and the next "
                    "one is due. For MONTHLY-interval plans this always coincides with "
                    "billing_cycle_end. For ANNUAL-interval plans it's independent — Stripe "
                    "only bills once a year, but credits still refresh monthly, so this "
                    "tracks the monthly refresh clock separately from the yearly "
                    "billing/contract clock."
                ),
                null=True,
            ),
        ),
    ]
