# expand-contract-step: contract
# Generated by Django 5.2.6 on 2026-06-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0029_usersubscription_next_credit_grant_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="interval",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("ANNUAL", "Annual"),
                    ("NONE", "None"),
                ],
                default="MONTHLY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PRO", "Pro"),
                    ("POWER", "Power"),
                    ("BETA", "Beta"),
                    ("CUSTOM", "Custom"),
                    ("STANDARD_ANNUAL", "Standard Annual"),
                    ("PRO_ANNUAL", "Pro Annual"),
                    ("POWER_ANNUAL", "Power Annual"),
                    ("TRIAL", "Trial"),
                    ("PRO_LICENSE", "Pro License"),
                    ("POWER_LICENSE", "Power License"),
                    ("CUSTOM_LICENSE_STARTER", "Custom License Starter"),
                    ("CUSTOM_LICENSE_MID", "Custom License Mid"),
                    ("CUSTOM_LICENSE_HIGH", "Custom License High"),
                ],
                help_text="Unique code for the plan",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standard"),
                    ("PRO", "Pro"),
                    ("POWER", "Power"),
                    ("BETA", "Beta"),
                    ("CUSTOM", "Custom"),
                    ("TRIAL", "Trial"),
                ],
                default="STANDARD",
                max_length=20,
            ),
        ),
    ]
