# Generated by Django 5.2.6 on 2026-07-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0030_alter_subscriptionplan_interval_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensesubscription",
            name="custom_price_cents",
            field=models.PositiveIntegerField(
                blank=True,
                help_text=(
                    "Negotiated monthly price for this license, overriding the plan's default price. "
                    "Set by super admin."
                ),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="licensesubscription",
            name="max_seats",
            field=models.PositiveIntegerField(
                default=1,
                help_text=(
                    "Maximum number of teacher seats allowed under this license. "
                    "0 = unlimited (e.g. for Custom contracts). Enforced on enrollment."
                ),
            ),
        ),
    ]
