# Generated by Django 5.2.6 on 2026-07-02 01:53

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0031_alter_licensesubscription_custom_price_cents_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="price_cents",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price in USD (e.g. 24.99)",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="overage_block_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Price per overage block in USD cents (e.g. 400 = $4.00)",
                max_digits=10,
            ),
        ),
    ]
