# expand-contract-step: contract
# Generated by Django 5.2.6 on 2026-07-02 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0032_remove_subscriptionplan_price_cents_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="price",
            new_name="price_cents",
        ),
    ]
