# Generated by Django 5.2.6 on 2026-07-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0033_rename_price_subscriptionplan_price_cents"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensesubscription",
            name="custom_price_cents",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text=(
                    "Negotiated monthly price for this license, overriding the"
                    " plan's default price. Set by super admin."
                ),
                max_digits=10,
                null=True,
            ),
        ),
    ]
