# Generated by Django 5.2.6 on 2026-07-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0034_alter_licensesubscription_custom_price_cents"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesubscription",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
