# Generated by Django 5.2.6 on 2026-07-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0035_licensesubscription_stripe_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensesubscription",
            name="contract_months",
            field=models.PositiveSmallIntegerField(
                default=12,
                help_text=(
                    "Contract duration in months. Schools can choose 9, 10, or"
                    " 12 month billing periods. This determines how far ahead"
                    " billing_cycle_end is set on creation and each renewal."
                ),
            ),
        ),
        migrations.AlterField(
            model_name="licensesubscription",
            name="custom_price_cents",
            field=models.IntegerField(
                blank=True,
                help_text=(
                    "Negotiated monthly price for this license, overriding the"  # noqa: B950
                    " plan's default price. Set by super admin."
                ),
                null=True,
            ),
        ),
    ]
