# Generated by Django 5.2.6 on 2026-07-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0036_alter_licensesubscription_contract_months_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolcreditallocation",
            name="next_credit_grant_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the next monthly credit refresh is due for this teacher under the license",
                null=True,
            ),
        ),
    ]
