# Generated by Django 5.2.6 on 2026-07-06 23:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0037_schoolcreditallocation_next_credit_grant_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesubscription",
            name="billing_method",
            field=models.CharField(
                choices=[
                    ("STRIPE", "Stripe"),
                    ("OFFLINE", "Offline / Manually Billed"),
                ],
                default="STRIPE",
                help_text=(
                    "STRIPE = billed automatically via a Stripe subscription. OFFLINE = "
                    "manually billed/renewed by a superadmin outside the platform "
                    "(wire transfer, PO, etc). Convertible in either direction."
                ),
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="LicenseBillingRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("CREATED_OFFLINE", "Created (Offline)"),
                            ("RENEWED_OFFLINE", "Renewed (Offline)"),
                            ("PLAN_CHANGE_OFFLINE", "Plan Changed (Offline)"),
                            ("SEATS_CHANGE_OFFLINE", "Seats Changed (Offline)"),
                            ("CONVERTED_TO_STRIPE", "Converted to Stripe"),
                            ("CONVERTED_TO_OFFLINE", "Converted to Offline"),
                            ("MANUAL_OVERAGE_GRANT", "Manual Overage Grant"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount_paid_cents", models.IntegerField(blank=True, null=True)),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        help_text="Invoice #, PO #, wire confirmation, check #, etc.",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "payment_method_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Wire transfer', 'Check', 'PO #4471'",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "previous_billing_cycle_end",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("new_billing_cycle_end", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "license_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_records",
                        to="billing.licensesubscription",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The superadmin who performed this action. Null if system/webhook-initiated.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_billing_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["license_subscription", "record_type"],
                        name="billing_lic_license_46741b_idx",
                    )
                ],
            },
        ),
    ]
