# Generated by Django 5.2.6 on 2026-07-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0038_licensesubscription_billing_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="overage_block_price",
            field=models.IntegerField(
                default=0,
                help_text="Price per overage block in USD cents (e.g. 400 = $4.00)",
            ),
        ),
    ]
