# Generated by Django 5.2.6 on 2026-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0039_alter_subscriptionplan_overage_block_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="pending_change_note",
            field=models.TextField(
                blank=True,
                help_text="""
                    Persisted, user-facing explanation of the scheduled change,
                    captured at schedule time so it stays stable and accurate
                    for the frontend to display on every visit, independent of
                    any later catalog/pricing changes. Null whenever pending_plan
                    is null.
                """,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="pending_change_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOWNGRADE", "Downgrade"),
                    ("UPGRADE_DEFERRED", "Upgrade (deferred)"),
                    ("LATERAL_DEFERRED", "Interval change (deferred)"),
                ],
                help_text="""
                    Why pending_plan is scheduled rather than applied immediately.
                    Null whenever pending_plan is null.
                """,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="stripe_schedule_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=""
                "ID of the Stripe SubscriptionSchedule managing a deferred plan "
                "change for this subscription, if any. Set whenever pending_plan"
                " is scheduled (StripeSubscriptionScheduleService "
                ".schedule_plan_change_on_stripe); cleared when the "
                "schedule is released — either because the scheduled change "
                "was cancelled, or because it was superseded by an immediate "
                "change instead. May remain set even after a scheduled change"
                " actually takes effect at renewal — Stripe schedules with an"
                " open-ended final phase don't self-terminate, so the same"
                " schedule is reused for the NEXT deferred change on this"
                " subscription rather than creating a new one each time.",
                max_length=255,
                null=True,
            ),
        ),
    ]
