# Generated by Django 5.2.6 on 2026-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0040_usersubscription_pending_change_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersubscription",
            name="pending_change_note",
            field=models.TextField(
                blank=True,
                help_text="Persisted, user-facing explanation of the scheduled change, captured at schedule time so it stays stable and accurate for the frontend to display on every visit, independent of any later catalog/pricing changes. Null whenever pending_plan is null.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscription",
            name="pending_change_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DOWNGRADE", "Downgrade"),
                    ("UPGRADE_DEFERRED", "Upgrade (deferred)"),
                    ("LATERAL_DEFERRED", "Interval change (deferred)"),
                ],
                help_text="Why pending_plan is scheduled rather than applied immediately. Null whenever pending_plan is null.",
                max_length=20,
                null=True,
            ),
        ),
    ]
