# Generated by Django 5.2.6 on 2026-07-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0041_alter_usersubscription_pending_change_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_overage_price_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Price ID for overage",
                max_length=100,
                null=True,
            ),
        ),
    ]
