# Generated by Django 5.2.6 on 2026-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0042_subscriptionplan_stripe_overage_price_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolcreditallocation",
            name="is_admin_allocation",
            field=models.BooleanField(
                default=False,
                help_text="True if this allocation belongs to the license's admin_user (a fixed analytics-only credit grant for the school admin's dashboard), not to an enrolled teacher. Excluded from teacher_count/seats_remaining/active_teacher_count, from the monthly_allocation overwrite on plan changes, and from LicenseSubscription.total_credits_consumed.",
            ),
        ),
    ]
