# Generated by Django 5.2.6 on 2026-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0043_schoolcreditallocation_is_admin_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditusagelog",
            name="feature",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Feature or service for which credits are being consumed",
                max_length=200,
                null=True,
            ),
        ),
    ]
