# Generated by Django 5.2.6 on 2026-07-23 08:53

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0044_alter_creditusagelog_feature"),
        ("classrooms", "0013_studentcourse_ai_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("INDIVIDUAL", "Individual"), ("LICENSE", "License")],
                        max_length=20,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            (
                                "INDIVIDUAL_SUBSCRIPTION_CHARGE",
                                "Individual Subscription Charge",
                            ),
                            (
                                "INDIVIDUAL_TRIAL_CONVERSION_CHARGE",
                                "Trial Conversion Charge",
                            ),
                            ("INDIVIDUAL_UPGRADE_CHARGE", "Individual Upgrade Charge"),
                            (
                                "INDIVIDUAL_OVERAGE_PURCHASE",
                                "Individual Overage Purchase",
                            ),
                            ("LICENSE_INITIAL_CHARGE", "License Initial Charge"),
                            ("LICENSE_SUBSCRIPTION_CHARGE", "License Renewal Charge"),
                            (
                                "LICENSE_PLAN_CHANGE_CHARGE",
                                "License Plan Change Charge",
                            ),
                            (
                                "LICENSE_SEAT_CHANGE_CHARGE",
                                "License Seat Increase Charge",
                            ),
                            ("LICENSE_OVERAGE_PURCHASE", "License Overage Purchase"),
                            ("LICENSE_OFFLINE_RENEWAL", "License Offline Renewal"),
                            (
                                "LICENSE_OFFLINE_PLAN_CHANGE",
                                "License Offline Plan Change",
                            ),
                            (
                                "LICENSE_OFFLINE_MANUAL_OVERAGE_GRANT",
                                "Manual Overage Grant",
                            ),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                            ("VOIDED", "Voided"),
                            ("MANUAL", "Recorded Manually (Offline)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "billing_method",
                    models.CharField(
                        choices=[("STRIPE", "Stripe"), ("OFFLINE", "Offline")],
                        default="STRIPE",
                        max_length=20,
                    ),
                ),
                (
                    "amount_cents",
                    models.IntegerField(
                        default=0, help_text="Gross amount charged/recorded, in cents."
                    ),
                ),
                ("refunded_amount_cents", models.IntegerField(default=0)),
                ("currency", models.CharField(default="usd", max_length=10)),
                (
                    "stripe_invoice_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="When the underlying billing event actually happened (may predate created_at for backfilled rows).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_billing_record",
                    models.ForeignKey(
                        blank=True,
                        help_text="Set for OFFLINE license events — links back to the detailed LicenseBillingRecord (payment reference, notes, etc).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_transactions",
                        to="billing.licensebillingrecord",
                    ),
                ),
                (
                    "license_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_transactions",
                        to="billing.licensesubscription",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin/superadmin who performed this action, for manual/offline events. Null for customer- or webhook-driven ones.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_billing_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        help_text="Denormalized from license_subscription at write time so history survives the license row changing, and permission checks don't need an extra join.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_transactions",
                        to="classrooms.school",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="For INDIVIDUAL transactions, the subscriber. For LICENSE transactions, the admin who initiated the action (if any) — the school is the real owner, tracked via `school`.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_transactions",
                        to="billing.usersubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "occurred_at"],
                        name="billing_bil_user_id_863eca_idx",
                    ),
                    models.Index(
                        fields=["license_subscription", "occurred_at"],
                        name="billing_bil_license_fe1cd4_idx",
                    ),
                    models.Index(
                        fields=["school", "occurred_at"],
                        name="billing_bil_school__70ca47_idx",
                    ),
                    models.Index(
                        fields=["source", "transaction_type"],
                        name="billing_bil_source_800dea_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("stripe_invoice_id__isnull", False)),
                        fields=("stripe_invoice_id",),
                        name="uniq_billing_txn_stripe_invoice",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("stripe_payment_intent_id__isnull", False)),
                        fields=("stripe_payment_intent_id",),
                        name="uniq_billing_txn_payment_intent",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("license_billing_record__isnull", False)),
                        fields=("license_billing_record",),
                        name="uniq_billing_txn_license_billing_record",
                    ),
                ],
            },
        ),
    ]
