# expand-contract-step: contract
# Generated by Django 5.2.6 on 2026-07-25 16:32

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0045_billingtransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="carry_over_max",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_bank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Ceiling on a user's total LIVE banked balance — MONTHLY + CARRY_OVER buckets combined (raw credits, display value × 1000). OVERAGE and MANUAL_GRANT credits are exempt and never counted against this. Null = no cap. At every rollover point, the carryover portion (never the monthly grant) is trimmed so the combined live total never exceeds this value.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="stripe_event_id",
            field=models.CharField(
                db_index=True, default="", max_length=255, unique=True
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="LicenseOveragePurchaseIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_blocks", models.PositiveIntegerField()),
                (
                    "allocations",
                    models.JSONField(
                        help_text="Mapping of teacher user UUID (string) -> blocks purchased."
                    ),
                ),
                (
                    "block_size_snapshot",
                    models.PositiveIntegerField(
                        help_text="plan.overage_block_size (raw credits per block) at purchase time."
                    ),
                ),
                (
                    "unit_price_cents_snapshot",
                    models.PositiveIntegerField(
                        help_text="plan.overage_block_price (cents per block) at purchase time."
                    ),
                ),
                (
                    "amount_cents",
                    models.PositiveIntegerField(
                        help_text="total_blocks * unit_price_cents_snapshot."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "stripe_checkout_session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_overage_purchase_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "license_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overage_purchase_intents",
                        to="billing.licensesubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["license_subscription", "status"],
                        name="billing_lic_license_8d4802_idx",
                    )
                ],
            },
        ),
    ]
