# Generated by Django 5.2.6 on 2026-07-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0046_remove_subscriptionplan_carry_over_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="carry_over_max",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Maximum raw credits that can be carried over (display value × 1000)",
            ),
        ),
    ]
