# Generated by Django 5.2.6 on 2026-07-29 15:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0047_subscriptionplan_carry_over_max"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingtransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    (
                        "INDIVIDUAL_SUBSCRIPTION_CHARGE",
                        "Individual Subscription Charge",
                    ),
                    ("INDIVIDUAL_TRIAL_CONVERSION_CHARGE", "Trial Conversion Charge"),
                    ("INDIVIDUAL_UPGRADE_CHARGE", "Individual Upgrade Charge"),
                    ("INDIVIDUAL_OVERAGE_PURCHASE", "Individual Overage Purchase"),
                    ("LICENSE_INITIAL_CHARGE", "License Initial Charge"),
                    ("LICENSE_SUBSCRIPTION_CHARGE", "License Renewal Charge"),
                    ("LICENSE_PLAN_CHANGE_CHARGE", "License Plan Change Charge"),
                    ("LICENSE_SEAT_CHANGE_CHARGE", "License Seat Increase Charge"),
                    ("LICENSE_OVERAGE_PURCHASE", "License Overage Purchase"),
                    ("LICENSE_OFFLINE_RENEWAL", "License Offline Renewal"),
                    ("LICENSE_OFFLINE_PLAN_CHANGE", "License Offline Plan Change"),
                    ("LICENSE_OFFLINE_MANUAL_OVERAGE_GRANT", "Manual Overage Grant"),
                    (
                        "LICENSE_OFFLINE_OVERAGE_PURCHASE",
                        "License Overage Purchase (Offline)",
                    ),
                    ("OTHER", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="licensebillingrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("CREATED_OFFLINE", "Created (Offline)"),
                    ("RENEWED_OFFLINE", "Renewed (Offline)"),
                    ("PLAN_CHANGE_OFFLINE", "Plan Changed (Offline)"),
                    ("SEATS_CHANGE_OFFLINE", "Seats Changed (Offline)"),
                    ("CONVERTED_TO_STRIPE", "Converted to Stripe"),
                    ("CONVERTED_TO_OFFLINE", "Converted to Offline"),
                    ("MANUAL_OVERAGE_GRANT", "Manual Overage Grant"),
                    (
                        "OFFLINE_OVERAGE_REQUEST_APPROVED",
                        "Offline Overage Request Approved",
                    ),
                ],
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="LicenseOverageOfflineRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_blocks", models.PositiveIntegerField()),
                (
                    "allocations",
                    models.JSONField(
                        help_text="Mapping of teacher user UUID (string) -> blocks requested."
                    ),
                ),
                (
                    "block_size_snapshot",
                    models.PositiveIntegerField(
                        help_text="plan.overage_block_size (raw credits per block) at request time."
                    ),
                ),
                (
                    "unit_price_cents_snapshot",
                    models.PositiveIntegerField(
                        help_text="plan.overage_block_price (cents per block) at request time."
                    ),
                ),
                (
                    "amount_cents_quoted",
                    models.PositiveIntegerField(
                        help_text="total_blocks * unit_price_cents_snapshot at request time."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "amount_confirmed_cents",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "payment_reference",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "payment_method_label",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("fulfilled_allocations", models.JSONField(blank=True, null=True)),
                ("skipped_allocations", models.JSONField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_billing_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overage_offline_requests",
                        to="billing.licensebillingrecord",
                    ),
                ),
                (
                    "license_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overage_offline_requests",
                        to="billing.licensesubscription",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_overage_offline_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license_overage_offline_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="billing_lic_status_fc0d2a_idx",
                    ),
                    models.Index(
                        fields=["license_subscription", "status"],
                        name="billing_lic_license_42bfe0_idx",
                    ),
                ],
            },
        ),
    ]
