# Generated by Django 5.2.6 on 2026-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0048_alter_billingtransaction_transaction_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="billingtransaction",
            name="receipt_url",
            field=models.URLField(
                blank=True,
                help_text="Stripe-hosted receipt/invoice page for this purchase.",
                max_length=500,
                null=True,
            ),
        ),
    ]
