# Generated by Django 5.2.6 on 2026-08-05 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0049_billingtransaction_receipt_url"),
        ("classrooms", "0016_school_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditusagelog",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Course the consuming task was performed under, when known. Null for tasks with no course context (e.g. custom AI chat, school-wide summaries) or for usage logged before this field existed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_usage_logs",
                to="classrooms.course",
            ),
        ),
    ]
