# Generated by Django 5.2.6 on 2026-08-05 20:17

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):

    # CREATE INDEX CONCURRENTLY cannot run inside a transaction. This index
    # backs SubscriptionService.refund_credits' `filter(task_id=...,
    # is_refunded=False).select_for_update()` lookup on credit_usage_log,
    # which is one of the largest tables in the schema (one row per bucket
    # drawn from, per AI call) — a plain AddIndex would take a SHARE lock
    # that blocks writes to the table for the whole build.
    atomic = False

    dependencies = [
        ("billing", "0050_creditusagelog_course"),
        ("classrooms", "0016_school_is_active"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="creditusagelog",
            index=models.Index(fields=["task_id"], name="billing_usagelog_task_idx"),
        ),
    ]
