# Generated by Django 5.2.6 on 2026-08-05 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0051_creditusagelog_task_id_index"),
        ("classrooms", "0016_school_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditusagelog",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="The school the billed user (teacher or school admin) belonged to at the moment these credits were consumed — a snapshot, deliberately NOT derived by joining to the user's current `school` FK. That field is mutable (a teacher can be reassigned to a different school after the fact), so joining live would retroactively misattribute historical usage to whichever school the user happens to belong to today. Null if the user had no school at consumption time (e.g. an individual, non-license teacher), or for usage logged before this field existed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="credit_usage_logs",
                to="classrooms.school",
            ),
        ),
    ]
