# Generated by Django 5.2.6 on 2026-08-05 21:43

from django.db import migrations
from django.db.models import OuterRef, Subquery


def backfill_school_from_wallet_user(apps, schema_editor):
    """
    Best-effort backfill for rows created before CreditUsageLog.school
    existed: set it from the wallet owner's *current* school.

    This is deliberately the same live-join logic the reporting code used
    to rely on (and which prompted adding the snapshot field in the first
    place) — for historical rows there is no way to recover which school
    the user actually belonged to at consumption time, so "their school
    now" is the best available approximation. It preserves today's
    reported totals (no regression on deploy) rather than resetting every
    school's historical token counts to near-zero. Only usage logged from
    this point forward gets a truly accurate, point-in-time snapshot via
    CreditWallet.consume_credits().
    """
    CreditUsageLog = apps.get_model("billing", "CreditUsageLog")
    CreditWallet = apps.get_model("billing", "CreditWallet")

    CreditUsageLog.objects.filter(school__isnull=True).update(
        school=Subquery(
            CreditWallet.objects.filter(pk=OuterRef("wallet_id")).values(
                "user__school"
            )[:1]
        )
    )


def noop_reverse(apps, schema_editor):
    # Nothing sensible to reverse to - a backfill isn't undoable without
    # losing the very history it was meant to preserve.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0052_creditusagelog_school"),
        # The backfill traverses wallet -> user -> school; without this
        # dependency the historical CustomUser model at this point in the
        # graph has no `school` field on a fresh database (FieldError:
        # "Cannot resolve keyword 'school'"), even though already-migrated
        # databases never notice.
        ("users", "0010_customuser_school_alter_customuser_user_type"),
    ]

    operations = [
        migrations.RunPython(backfill_school_from_wallet_user, noop_reverse),
    ]
