# Generated by Django 5.2.6 on 2026-08-08 12:38

from django.db import migrations, models
from django.db.models import F


def backfill_existing_events_as_succeeded(apps, schema_editor):
    """
    Settle every pre-existing ledger row as SUCCEEDED.

    The justification is NOT "every surviving row was processed
    successfully" — that isn't quite true. A request killed by gunicorn's
    --timeout mid-handler, or one whose handler raised a BaseException,
    left its row behind with the work incomplete, and those rows exist.

    The real justification: the OLD code deleted a row whenever its handler
    raised, so no surviving row was ever *recorded* as a failure — and any
    crash-orphans among them are long past Stripe's ~3-day retry window and
    are therefore unrecoverable no matter what we mark them. Backfilling
    those to PROCESSING would only create permanently-stuck rows that the
    new sweeper alarms on forever with no possible remediation.

    completed_at is set to processed_at because that creation timestamp is
    the only time information these rows carry.

    Filtered on the schema default so re-running this is a no-op.
    """
    StripeEvent = apps.get_model("billing", "StripeEvent")
    StripeEvent.objects.filter(status="PROCESSING").update(
        status="SUCCEEDED",
        claimed_at=F("processed_at"),
        completed_at=F("processed_at"),
        attempts=1,
    )


def noop_reverse(apps, schema_editor):
    """The columns are dropped by the reversed AddFields; nothing to restore."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0053_backfill_creditusagelog_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeevent",
            name="attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="How many times a worker has claimed this event."
            ),
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current (or most recent) processing claim was acquired. Doubles as the fencing token for the terminal write, and is what identifies a claim abandoned by a killed worker.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When processing reached a terminal state (SUCCEEDED/FAILED).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="last_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Truncated exception text from the most recent failed attempt.",
            ),
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "Processing"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PROCESSING",
                help_text="Processing claim state. Only SUCCEEDED suppresses a redelivery — see StripeEventStatus.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="processed_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="When this event was FIRST seen. Write-once (auto_now_add) — it is NOT the completion time; see completed_at for that. Kept under this name because Meta.ordering and the backfill_billing_transactions command both read it.",
            ),
        ),
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(
                fields=["status", "claimed_at"], name="billing_str_status_1866f2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stripeevent",
            index=models.Index(
                fields=["status", "completed_at"], name="billing_str_status_a68c9b_idx"
            ),
        ),
        migrations.RunPython(backfill_existing_events_as_succeeded, noop_reverse),
    ]
