# Generated by Django 5.2.6 on 2026-08-10 11:05

from django.db import migrations, models
from django.db.models import F


def backfill_consumption_window_start(apps, schema_editor):
    """
    Seed the new monthly consumption window from billing_cycle_start.

    total_credits_consumed is measured against a MONTHLY budget
    (max_seats * plan.monthly_credits) but used to be reset only at
    contract renewal — once every contract_months. Existing rows are
    therefore carrying an accumulated figure that may span many months.

    billing_cycle_start, not now(): for a license already six months into
    a twelve-month contract, seeding the window in the past means the very
    next monthly refresh opens a correct window immediately. Seeding it to
    now() would instead leave the inflated counter in force for one more
    month, i.e. keep the bug alive for exactly the licenses that have been
    suffering from it longest.
    """
    LicenseSubscription = apps.get_model("billing", "LicenseSubscription")
    LicenseSubscription.objects.filter(consumption_window_start__isnull=True).update(
        consumption_window_start=F("billing_cycle_start")
    )


def noop_reverse(apps, schema_editor):
    """Nothing to undo: the column is dropped by the reverse of AddField."""


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0054_stripeevent_attempts_stripeevent_claimed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensesubscription",
            name="consumption_window_start",
            field=models.DateTimeField(
                blank=True,
                help_text="Start of the monthly window total_credits_consumed is counting. Exists so the reset is idempotent and self-serializing: the monthly refresh runs once per TEACHER, so a naive reset would fire N times a month and discard consumption recorded between teachers refreshed on different days. Null means never reset (pre-migration rows); it is backfilled to billing_cycle_start.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="licensesubscription",
            name="total_credits_consumed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total raw credits consumed by all teachers under this license in the current MONTHLY consumption window (see consumption_window_start). Measured against max_seats * plan.monthly_credits, which is a monthly figure — so this must be reset monthly, NOT once per contract.",
            ),
        ),
        migrations.RunPython(backfill_consumption_window_start, noop_reverse),
    ]
