# Generated by Django 5.2.6 on 2026-08-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0056_liveqarun"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="cancelled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user (or a Stripe-side action) scheduled this subscription to stop renewing. Set alongside auto_renew=False by the cancel endpoint and by the customer.subscription.updated webhook; cleared again on resume. Purely informational — auto_renew remains the operative flag — but it is the only record of WHEN the cancellation was requested, which the frontend shows back to the user. Null for trials (whose auto_renew is False from birth without any cancellation having happened) and for rows cancelled before this field existed.",
                null=True,
            ),
        ),
    ]
