# Generated by Django 5.2.6 on 2026-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0057_usersubscription_cancelled_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licensebillingrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("CREATED_OFFLINE", "Created (Offline)"),
                    ("RENEWED_OFFLINE", "Renewed (Offline)"),
                    ("PLAN_CHANGE_OFFLINE", "Plan Changed (Offline)"),
                    ("SEATS_CHANGE_OFFLINE", "Seats Changed (Offline)"),
                    ("CONVERTED_TO_STRIPE", "Converted to Stripe"),
                    ("CONVERTED_TO_OFFLINE", "Converted to Offline"),
                    ("MANUAL_OVERAGE_GRANT", "Manual Overage Grant"),
                    (
                        "OFFLINE_OVERAGE_REQUEST_APPROVED",
                        "Offline Overage Request Approved",
                    ),
                    ("CANCELLED", "Cancelled"),
                ],
                max_length=40,
            ),
        ),
    ]
