# Generated by Django 5.2.6 on 2026-09-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0061_add_audit_table_time_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveqarun",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RUNNING", "Running"),
                    ("PASSED", "Passed"),
                    ("FAILED", "Failed"),
                    ("SKIPPED", "Skipped (not enabled here)"),
                    ("ERROR", "Could not run (misconfigured)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
