# expand-contract-step: expand
# Choices-only AlterFields, flagged by the safety gate as "NOT NULL without a
# default" because its predicate cannot tell a nullability change from an
# alteration that only touches `choices`. Both columns already exist and are
# already NOT NULL with data; `choices` is Django-level validation and emits no
# DDL. Verified purely ADDITIVE - BillingTransaction.status gains DISPUTED and
# DISPUTE_LOST, CreditLedger.ledger_type gains DISPUTE_REVERSAL, and nothing is
# removed - so no existing row can be left holding a value the field no longer
# accepts. Nothing to backfill.
# Generated by Django 5.2.6 on 2026-09-08 08:27

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0062_liveqarun_skipped_and_error_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="creditwallet",
            name="dispute_deficit_credits",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Credits owed back after a lost chargeback that were already consumed and so could not be reclaimed from a bucket.",
            ),
        ),
        migrations.AddField(
            model_name="creditwallet",
            name="is_consumption_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Blocks further credit consumption while an unsettled dispute deficit exists. Cleared by hand once the account is settled.",
            ),
        ),
        migrations.AlterField(
            model_name="billingtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                    ("VOIDED", "Voided"),
                    ("MANUAL", "Recorded Manually (Offline)"),
                    ("DISPUTED", "Disputed (chargeback open)"),
                    ("DISPUTE_LOST", "Dispute lost (charged back)"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditledger",
            name="ledger_type",
            field=models.CharField(
                choices=[
                    ("CONSUME", "Consume"),
                    ("REFUND", "Refund"),
                    ("GRANT", "Grant"),
                    ("EXPIRE", "Expire"),
                    ("PURCHASE", "Purchase"),
                    ("PLAN_CHANGE", "Plan Change"),
                    ("DISPUTE_REVERSAL", "Dispute Reversal"),
                ],
                help_text="Type of credit ledger",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentDispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_dispute_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("warning_needs_response", "Inquiry: needs response"),
                            ("warning_under_review", "Inquiry: under review"),
                            ("warning_closed", "Inquiry: closed"),
                            ("needs_response", "Chargeback: needs response"),
                            ("under_review", "Chargeback: under review"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                ("amount_cents", models.IntegerField(default=0)),
                (
                    "fee_cents",
                    models.IntegerField(
                        default=0,
                        help_text="Stripe's dispute fee. Not returned even on a win.",
                    ),
                ),
                ("currency", models.CharField(default="usd", max_length=10)),
                ("evidence_due_by", models.DateTimeField(blank=True, null=True)),
                ("funds_withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("funds_reinstated_at", models.DateTimeField(blank=True, null=True)),
                ("credits_reversed", models.BooleanField(default=False)),
                ("credits_reversed_amount", models.PositiveIntegerField(default=0)),
                (
                    "credits_deficit_amount",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Portion of the reversal that was already spent and could not be reclaimed.",
                    ),
                ),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "raw_payload",
                    models.JSONField(
                        blank=True,
                        help_text="Last Dispute object received, for audit.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes",
                        to="billing.billingtransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_disputes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="billing_pay_status_f6057f_idx",
                    )
                ],
            },
        ),
    ]
