# expand-contract-step: expand
# Same shape as 0063: the only flagged operation is a choices-only AlterField on
# CreditLedger.ledger_type, adding DISPUTE_REVERSAL and REFUND_REVERSAL. Purely
# additive, no value removed, no DDL, nothing to backfill. The column is
# pre-existing and already NOT NULL.
# Generated by Django 5.2.6 on 2026-09-09 15:30

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0063_payment_disputes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentRefund",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "stripe_charge_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("amount_captured_cents", models.PositiveIntegerField(default=0)),
                (
                    "amount_refunded_cents",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cumulative across all refunds on the charge. Monotonic.",
                    ),
                ),
                ("currency", models.CharField(default="usd", max_length=10)),
                (
                    "credits_granted",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Credits this payment bought, summed from its grant ledger rows.",
                    ),
                ),
                (
                    "credits_reversed",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Cumulative credits reclaimed for this payment.",
                    ),
                ),
                (
                    "credits_deficit",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Portion of the reversal that was already spent and so could not be reclaimed. Recorded as debt; usage history is never rewritten.",
                    ),
                ),
                (
                    "blocks_restored_by_wallet",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "retain_credits",
                    models.BooleanField(
                        default=False,
                        help_text="Deliberate business decision to absorb the loss and let the customer keep the credits. Set from Stripe refund metadata.",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="creditledger",
            name="stripe_payment_intent_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe PaymentIntent this entry is attributable to, when the entry came from a payment. Used to attribute a refund or chargeback back to the exact credits it bought.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="creditwallet",
            name="refund_deficit_credits",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Credits owed back after a refund that were already consumed and so could not be reclaimed from a bucket.",
            ),
        ),
        migrations.AlterField(
            model_name="creditledger",
            name="ledger_type",
            field=models.CharField(
                choices=[
                    ("CONSUME", "Consume"),
                    ("REFUND", "Refund"),
                    ("GRANT", "Grant"),
                    ("EXPIRE", "Expire"),
                    ("PURCHASE", "Purchase"),
                    ("PLAN_CHANGE", "Plan Change"),
                    ("DISPUTE_REVERSAL", "Dispute Reversal"),
                    ("REFUND_REVERSAL", "Refund Reversal"),
                ],
                help_text="Type of credit ledger",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="creditwallet",
            name="is_consumption_blocked",
            field=models.BooleanField(
                default=False,
                help_text="Blocks further credit consumption while an unsettled dispute or refund deficit exists. Cleared by hand once the account is settled.",
            ),
        ),
        # NOTE: the `bill_ledger_pi_idx` index on CreditLedger is
        # deliberately NOT created here. It is built CONCURRENTLY in 0065,
        # together with the backfill that populates the column — a plain
        # CREATE INDEX on the fastest-growing table in the schema takes an
        # ACCESS EXCLUSIVE lock for the whole build and would block every
        # credit consumption in the product while it ran.
        migrations.AddField(
            model_name="paymentrefund",
            name="billing_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="billing.billingtransaction",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrefund",
            index=models.Index(
                fields=["-created_at"], name="billing_pay_created_115895_idx"
            ),
        ),
    ]
