# Generated by Django 5.2.6 on 2026-09-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0065_backfill_ledger_payment_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdispute",
            name="deficit_by_wallet",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
