# Generated by Django 5.2.6 on 2026-09-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0066_dispute_deficit_by_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeevent",
            name="handler_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When a worker actually began running the handler for the current claim — NOT when the claim was taken. The gap between the two is the whole point: a claim with no start means the worker died before touching anything and the event can be safely re-dispatched, while a claim WITH a start may have got part-way through irreversible Stripe calls and must not be replayed automatically.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="recovery_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many times the sweeper has re-dispatched this event after a worker abandoned its claim. Capped, so a task that dies the same way every time stops being retried and starts being reported.",
            ),
        ),
    ]
