# Generated by Django 5.2.6 on 2026-09-11 15:39

import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0067_stripe_event_recovery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price_cents",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Base subscription price in CENTS, matching Stripe's `unit_amount` exactly — STANDARD is 1499, not 14.99. The field name is right and the old help text was wrong; entering dollars here would under-bill by 100x and the nightly reconciliation would report it as drift against Stripe. Decimal rather than integer only for historical reasons.",
                max_digits=10,
            ),
        ),
        migrations.CreateModel(
            name="PriceReconciliationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "stripe_account_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_api_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("plans_checked", models.PositiveIntegerField(default=0)),
                ("prices_checked", models.PositiveIntegerField(default=0)),
                ("matched_count", models.PositiveIntegerField(default=0)),
                ("alert_count", models.PositiveIntegerField(default=0)),
                ("unavailable_count", models.PositiveIntegerField(default=0)),
                ("summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="billing_pri_started_eb4e33_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceReconciliationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plan_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "plan_category",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "price_kind",
                    models.CharField(
                        choices=[
                            ("BASE", "Base subscription price"),
                            ("OVERAGE", "Overage block price"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price_id", models.CharField(blank=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("MATCHED", "Matched"),
                            ("DRIFT_DETECTED", "Drift detected"),
                            ("MISSING_PRICE_ID", "Missing price id"),
                            ("INVALID_PRICE", "Invalid price"),
                            ("INACTIVE_PRICE", "Inactive price"),
                            ("ACCOUNT_MISMATCH", "Stripe account mismatch"),
                            ("STRIPE_UNAVAILABLE", "Stripe unavailable"),
                            ("CONFIGURATION_ERROR", "Configuration error"),
                            ("NOT_APPLICABLE", "Not applicable"),
                        ],
                        max_length=24,
                    ),
                ),
                ("expected_amount", models.IntegerField(blank=True, null=True)),
                ("stripe_amount", models.IntegerField(blank=True, null=True)),
                (
                    "expected_currency",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "stripe_currency",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("expected_active", models.BooleanField(blank=True, null=True)),
                ("stripe_active", models.BooleanField(blank=True, null=True)),
                (
                    "expected_product",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_product",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("expected_recurring", models.JSONField(blank=True, null=True)),
                ("stripe_recurring", models.JSONField(blank=True, null=True)),
                ("mismatched_fields", models.JSONField(blank=True, default=list)),
                (
                    "error_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_reconciliations",
                        to="billing.subscriptionplan",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="billing.pricereconciliationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["plan_name", "price_kind"],
                "indexes": [
                    models.Index(
                        fields=["status", "-detected_at"],
                        name="billing_pri_status_bbaa82_idx",
                    ),
                    models.Index(
                        fields=["plan", "price_kind"],
                        name="billing_pri_plan_id_fa1b17_idx",
                    ),
                ],
            },
        ),
    ]
