# expand-contract-step: expand
# Choices-only AlterField on PriceReconciliationResult.status, adding
# SYNCHRONIZED. The table itself is created one migration earlier in 0068, so in
# any environment reaching this it is either empty or holds only rows this code
# wrote. Purely additive, nothing removed, nothing to backfill.
# Generated by Django 5.2.6 on 2026-09-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0068_price_reconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricereconciliationresult",
            name="previous_local_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pricereconciliationresult",
            name="previous_local_product",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pricereconciliationresult",
            name="synced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pricereconciliationresult",
            name="synced_fields",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="pricereconciliationrun",
            name="synced_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="pricereconciliationresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("MATCHED", "Matched"),
                    ("SYNCHRONIZED", "Synchronized from Stripe"),
                    ("DRIFT_DETECTED", "Drift detected"),
                    ("MISSING_PRICE_ID", "Missing price id"),
                    ("INVALID_PRICE", "Invalid price"),
                    ("INACTIVE_PRICE", "Inactive price"),
                    ("ACCOUNT_MISMATCH", "Stripe account mismatch"),
                    ("STRIPE_UNAVAILABLE", "Stripe unavailable"),
                    ("CONFIGURATION_ERROR", "Configuration error"),
                    ("NOT_APPLICABLE", "Not applicable"),
                ],
                max_length=24,
            ),
        ),
    ]
