# Generated by Django 5.2.6 on 2026-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0069_price_sync_audit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditwallet",
            name="dispute_deficit_credits",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="Credits owed back after a lost chargeback that were already consumed and so could not be reclaimed from a bucket.",
            ),
        ),
        migrations.AlterField(
            model_name="creditwallet",
            name="is_consumption_blocked",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Blocks further credit consumption while an unsettled dispute or refund deficit exists. Cleared by hand once the account is settled.",
            ),
        ),
        migrations.AlterField(
            model_name="creditwallet",
            name="refund_deficit_credits",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="Credits owed back after a refund that were already consumed and so could not be reclaimed from a bucket.",
            ),
        ),
        migrations.AlterField(
            model_name="paymentdispute",
            name="deficit_by_wallet",
            field=models.JSONField(
                blank=True,
                db_default=models.Value({}, output_field=models.JSONField()),
                default=dict,
            ),
        ),
        migrations.AlterField(
            model_name="pricereconciliationresult",
            name="previous_local_product",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="pricereconciliationresult",
            name="synced",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AlterField(
            model_name="pricereconciliationresult",
            name="synced_fields",
            field=models.JSONField(
                blank=True,
                db_default=models.Value([], output_field=models.JSONField()),
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="pricereconciliationrun",
            name="synced_count",
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
        migrations.AlterField(
            model_name="stripeevent",
            name="recovery_attempts",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="How many times the sweeper has re-dispatched this event after a worker abandoned its claim. Capped, so a task that dies the same way every time stops being retried and starts being reported.",
            ),
        ),
    ]
