# Generated by Django 5.2.6 on 2026-09-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0070_db_defaults_for_rollback"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripeevent",
            name="auto_replay_attempts",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                help_text="How many times the allow-listed auto-replay task has re-run this event's handler (billing/event_replay.py). Capped, so an event that fails the same way forever stops being retried and starts being reported.",
            ),
        ),
        migrations.AddField(
            model_name="stripeevent",
            name="auto_replay_note",
            field=models.CharField(
                blank=True,
                db_default="",
                default="",
                help_text="Why the auto-replay task did or did not re-run this event, recorded on the row so the decision outlives the logs.",
                max_length=200,
            ),
        ),
    ]
