# Generated by Django 5.2.6 on 2026-09-19 11:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0071_stripeevent_auto_replay_attempts_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseStripeMutationIntent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("CANCEL", "Cancel at period end"),
                            ("UPDATE_SEATS", "Update seats"),
                            ("CHANGE_PLAN", "Change plan"),
                            ("CONVERT_TO_OFFLINE", "Convert to offline billing"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            (
                                "STRIPE_APPLIED",
                                "Applied at Stripe, not yet recorded locally",
                            ),
                            ("ESCALATED", "Escalated to a human"),
                            ("COMPLETE", "Complete"),
                            ("COMPENSATED", "Reverted at Stripe"),
                            ("FAILED", "Not applied at Stripe"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("stripe_subscription_id", models.CharField(max_length=255)),
                (
                    "requested_change",
                    models.JSONField(
                        help_text='What was asked for and what it replaced, e.g. {"old_max_seats": 10, "new_max_seats": 15} — enough to finish the local write, or to revert Stripe, without re-deriving it.'
                    ),
                ),
                (
                    "stripe_result",
                    models.JSONField(
                        blank=True,
                        help_text="What Stripe returned that the local write needs (invoice id, amount paid).",
                        null=True,
                    ),
                ),
                ("failure_reason", models.TextField(blank=True, null=True)),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "license_subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stripe_mutation_intents",
                        to="billing.licensesubscription",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_stripe_mutation_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_license_stripe_mutation_intents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["license_subscription", "status"],
                        name="billing_lic_license_1085ab_idx",
                    ),
                    models.Index(
                        fields=["status", "updated_at"],
                        name="billing_lic_status_7d4780_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("status__in", ("PENDING", "STRIPE_APPLIED", "ESCALATED"))
                        ),
                        fields=("license_subscription",),
                        name="one_inflight_stripe_mutation_per_licence",
                    )
                ],
            },
        ),
    ]
