# Generated by Django 5.2.6 on 2026-10-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0072_license_stripe_mutation_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolcreditallocation",
            name="grant_anchor_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The moment this teacher's monthly refreshes are counted from (H-88): set at enrolment, re-enrolment, reactivation and each license renewal. Each refresh is due at this plus k months, so a 31st gives 28 Feb, 31 Mar, 30 Apr. NULL on rows older than the field: see refresh_timing.allocation_anchor.",
                null=True,
            ),
        ),
    ]
