# Generated by Django 5.2.6 on 2025-10-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submission_date", models.DateTimeField(auto_now_add=True)),
                (
                    "answers",
                    models.JSONField(
                        help_text="Student answers in JSON format, structured to match assignment questions"
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0.0,
                        help_text="Final score awarded to the submission",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "feedback",
                    models.JSONField(
                        blank=True,
                        help_text="Feedback provided for each question",
                        null=True,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="assignments.assignment",
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_date"],
            },
        ),
    ]
