# Generated by Django 5.2.6 on 2026-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="graded_at",
            field=models.DateField(
                blank=True,
                help_text="The time student submission was graded",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="grading_confidence",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
