# Generated by Django 5.2.6 on 2026-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentsubmission_graded_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubmission",
            name="graded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time student submission was graded",
                null=True,
            ),
        ),
    ]
