# Generated by Django 5.2.6 on 2026-01-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_alter_studentsubmission_graded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="ai_feedback",
            field=models.JSONField(
                blank=True,
                help_text="AI feedback provided for each question",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="ai_graded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time student submission was graded by AI",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="ai_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="AI score awarded to the submission",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="regraded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time the AI grade was modified by a human",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="was_regraded",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the AI grade was modified by a human",
            ),
        ),
    ]
