# Generated by Django 5.2.6 on 2026-02-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_studentsubmission_ai_feedback_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="ai_grading_completed_at",
            field=models.DateField(
                blank=True,
                help_text="The time the ai finished grading the student submission",
                null=True,
            ),
        ),
    ]
