# Generated by Django 5.2.6 on 2026-02-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_studentsubmission_ai_grading_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="extraction_confidence",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
