# Generated by Django 5.2.6 on 2026-02-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_studentsubmission_extraction_confidence"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="formatted_grade",
            field=models.TextField(blank=True, null=True),
        ),
    ]
