# Generated by Django 5.2.6 on 2026-02-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0008_studentsubmission_formatted_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="raw_input",
            field=models.TextField(
                blank=True,
                help_text="Raw student input, as submitted in the form",
                null=True,
            ),
        ),
    ]
