# Generated by Django 5.2.6 on 2026-03-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0028_alter_assignment_raw_input_hash"),
        ("classrooms", "0012_studentcourse_auto_added"),
        ("students", "0010_batchuploadsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchuploadsession",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_upload_sessions",
                to="classrooms.course",
            ),
        ),
        migrations.AddField(
            model_name="batchuploadsession",
            name="task_type",
            field=models.CharField(
                choices=[("submission", "Submission"), ("assignment", "Assignment")],
                default="submission",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="batchuploadsession",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_upload_sessions",
                to="assignments.assignment",
            ),
        ),
    ]
