# Generated by Django 5.2.6 on 2026-03-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0011_batchuploadsession_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchuploadsession",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("submission", "Submission"),
                    ("assignment", "Assignment"),
                    ("grade", "Grade"),
                ],
                default="submission",
                max_length=255,
            ),
        ),
    ]
