# Generated by Django 5.2.6 on 2026-04-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0012_alter_batchuploadsession_task_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="max_points",
            field=models.IntegerField(
                blank=True,
                help_text="Maximum points available for this assignment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="score_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Score as a percentage of total possible points (calculated from score and "
                "assignment max_points)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
