# Generated by Django 5.2.6 on 2026-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0013_studentsubmission_max_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubmission",
            name="score_percentage",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                help_text="Score as a percentage of total possible points "
                "(calculated from score and assignment max_points)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
