# Generated by Django 5.2.6 on 2026-04-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0014_alter_studentsubmission_score_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Whether the grade has been released to the student",
            ),
        ),
    ]
