# Generated by Django 5.2.6 on 2026-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0015_studentsubmission_is_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="grading_task_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the Celery task handling the scheduled grading",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="scheduled_grading_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time this submission is scheduled to be graded",
                null=True,
            ),
        ),
    ]
