# Generated by Django 5.2.6 on 2026-07-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0017_backgroundprocessingtask"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of times the student has submitted this assignment.",
            ),
        ),
    ]
