# Generated by Django 5.2.6 on 2026-07-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0018_studentsubmission_attempt_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentsubmission",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(
                blank=True,
                default=0,
                help_text="Number of times the student has submitted this assignment.",
                null=True,
            ),
        ),
    ]
