# Generated by Django 5.2.6 on 2026-08-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0019_alter_studentsubmission_attempt_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="grading_started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the current (or most recent) grading claim was acquired. Used to detect and reclaim a stale RUNNING claim left behind by a crashed worker.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="grading_state",
            field=models.CharField(
                choices=[
                    ("IDLE", "Idle"),
                    ("RUNNING", "Running"),
                    ("DONE", "Done"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="IDLE",
                help_text="Idempotency claim for the grading pipeline. RUNNING means a worker currently holds the claim; see GradingState's docstring.",
                max_length=20,
            ),
        ),
    ]
