# Generated by Django 5.2.6 on 2026-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0020_studentsubmission_grading_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="needs_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="The two independent AI graders disagreed on at least one question (see feedback['second_opinion']) — the teacher's review queue filters on this. Cleared by mark-reviewed or a manual grade override.",
            ),
        ),
        migrations.AddField(
            model_name="studentsubmission",
            name="review_reasons",
            field=models.JSONField(
                blank=True,
                help_text="Why this submission needs (or needed) review — per-question grader-disagreement entries, and the teacher's resolution once reviewed.",
                null=True,
            ),
        ),
    ]
