# Generated by Django 5.2.6 on 2026-08-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0021_studentsubmission_needs_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="review_severity",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="0-1: the worst grader-disagreement gap on this submission as a fraction of that question's points. Lets the review queue order 'definitely review' (excellent-vs-poor) ahead of 'borderline' (adjacent levels): ?needs_review=true&ordering=-review_severity.",
                null=True,
            ),
        ),
    ]
