# Generated by Django 5.2.6 on 2026-08-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0022_studentsubmission_review_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsubmission",
            name="review_tier",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Worst disagreement severity on this submission (critical / moderate / borderline), denormalised from review_reasons so the queue can filter on it - review_reasons is a JSONField and cannot be filtered. ?needs_review=true&review_tier=critical.",
                max_length=16,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="studentsubmission",
            name="review_severity",
            field=models.FloatField(
                blank=True,
                db_index=True,
                help_text="0-1 tier-weighted sort key for the review queue: the tier picks the band (critical 0.67-1.0, moderate 0.33-0.67, borderline 0-0.33) and the disagreement's point gap orders within it. Weighted rather than the raw gap fraction because a disagreement is also 'critical' when the graders are 2+ rubric levels apart, which can happen at a small gap - ordering on the raw fraction buried those below milder ones. ?needs_review=true&ordering=-review_severity.",
                null=True,
            ),
        ),
    ]
