# Generated by Django 5.2.6 on 2026-08-19 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0036_backfill_assignment_rigor"),
        ("students", "0024_repair_raw_input_json"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studentsubmission",
            index=models.Index(
                fields=["assignment", "-submission_date"],
                name="submission_assignment_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentsubmission",
            index=models.Index(fields=["graded_at"], name="submission_graded_at_idx"),
        ),
    ]
