# Generated by Django 5.2.6 on 2026-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0025_student_submission_hot_path_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundprocessingtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("assignment_extraction", "Assignment Extraction"),
                    ("assignment_reextraction", "Assignment Re-extraction"),
                    ("batch_assignment_upload", "Batch Assignment Upload"),
                    ("answer_extraction", "Answer Extraction"),
                    ("batch_answer_upload", "Batch Answer Upload"),
                    ("submission_grading", "Submission Grading"),
                    ("batch_submission_grading", "Batch Submission Grading"),
                    ("formatted_grade", "Formatted Grade"),
                    ("student_summary", "Student Summary"),
                ],
                max_length=64,
            ),
        ),
    ]
