# Generated by Django 5.2.6 on 2026-09-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0029_background_task_item_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchuploadsession",
            name="credits_exhausted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
