"""
Django settings for AutoGrader project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

love God
"""

# import logging
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from celery.schedules import crontab
from environ import Env

env = Env()
env.read_env(".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "\n\n{name} {levelname} {asctime} {module} {process:d} {thread:d} {message}\n\n",
            "style": "{",
        },
        "simple": {
            "format": "\n\n[%(asctime)s] %(levelname)s %(message)s\n\n",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": [
                "console",
            ],
            "level": "ERROR",
        },
        "ERROR_REPORT": {
            "handlers": ["console"],
            "level": "ERROR",
        },
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")
FRONTEND_DOMAIN = env.str("FRONTEND_DOMAIN")

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = env.str("ENVIRONMENT")

if ENVIRONMENT == "prod":
    DEBUG = False
elif ENVIRONMENT == "dev":
    DEBUG = False
elif ENVIRONMENT == "local":
    DEBUG = True

APPEND_SLASH = False

ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://([a-z0-9-]+\.)?localhost(:[0-9]+)?$",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    "cloudinary_storage",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary",
    "django.contrib.humanize",
    "django_filters",
    "djoser",
    "anymail",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    "django_extensions",
    "users",
    "classrooms",
    "assignments",
    "students",
    "grading",
    "ocr_processor",
    "ai_processor",
    "dashboard",
    "billing",
    "django_celery_results",
    "django_celery_beat",
    # Third-party packages
    "encrypted_model_fields",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "users.middleware.UserActivityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AutoGrader.urls"
AUTH_USER_MODEL = "users.CustomUser"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AutoGrader.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_CONFIG = {
    "conn_max_age": 0,
    "conn_health_checks": True,
}

if ENVIRONMENT == "local":
    DATABASES = {
        "default": dj_database_url.config(
            default=env.str("DATABASE_URI_LOCAL"), **DATABASE_CONFIG
        )
    }
elif ENVIRONMENT == "dev":
    DATABASES = {
        "default": dj_database_url.config(
            default=env.str("DATABASE_URI_DEV"), **DATABASE_CONFIG
        )
    }
else:
    DATABASES = {
        "default": dj_database_url.config(
            default=env.str("DATABASE_URI"), **DATABASE_CONFIG
        ),
        "OPTIONS": {
            "prepare_threshold": None,  # or psycopg2 alternative
        },
    }
DISABLE_SERVER_SIDE_CURSORS = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Celery Configuration Options
CELERY_BROKER_URL = (
    env.str("REDIS_LOCAL_URL")
    if ENVIRONMENT == "local"
    else env.str("REDIS_DEV_URL") if ENVIRONMENT == "dev" else env.str("REDIS_PROD_URL")
)
CELERY_RESULT_BACKEND = (
    env.str("REDIS_LOCAL_URL")
    if ENVIRONMENT == "local"
    else env.str("REDIS_DEV_URL") if ENVIRONMENT == "dev" else env.str("REDIS_PROD_URL")
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
# With CELERY_TASK_ACKS_LATE=True, Redis redelivers a task's message to
# another worker once visibility_timeout elapses without an ack — i.e. it
# assumes the original worker died. A grading run (several sequential AI
# calls, each with its own retries — see assignments.tasks.grade_engine_async)
# can legitimately take longer than the previous 600s value, which caused
# Redis to redeliver a still-running grading task to a second worker,
# double-billing the teacher. Raised well above
# students.services.GRADING_TASK_TIME_LIMIT_SECONDS (Celery's own hard kill
# point for that task) so a healthy, still-running task is never mistaken
# for a dead one. The grading claim in students.services
# (_claim_submission_for_grading) is the actual correctness guarantee against
# duplicate execution — this setting just keeps ordinary redeliveries rare
# in the first place, since even a caught duplicate wastes a worker slot and
# an API round trip before being skipped.
CELERY_BROKER_TRANSPORT_OPTIONS = {
    "visibility_timeout": 3600,  # 1 hour
}

# Tier 0 grading: OBJECTIVE questions whose answer matches an option
# unambiguously are graded in Python against the stored answer key — no
# AI call, no credits. Claim-only: any ambiguity defers to the AI, so
# turning this on can only remove AI error. False restores the previous
# behavior exactly (production rollback lever). See
# ai_processor/objective_grading.py.
GRADING_DETERMINISTIC_OBJECTIVE = True

# Structured output for grading calls: enforce json_schema contracts
# (ai_processor/grading_schemas.py) instead of free-form json_object.
# Kill switch in case an OpenRouter fallback model rejects json_schema —
# False restores the previous free-form behavior.
GRADING_RESPONSE_SCHEMA_ENABLED = True

# Mechanical evidence verification (ai_processor/evidence.py): every
# points-awarding evaluation must cite at least one verbatim quote from
# the student's answer, string-checked in code.
#   "strict" — fabricated/absent evidence rejects the response (retried,
#              like a completeness failure)
#   "log"    — verify + annotate evaluations, never reject
#   "off"    — evidence is not inspected at all
GRADING_EVIDENCE_ENFORCEMENT = "strict"

# Selective blind second opinion (ai_processor/second_opinion.py): a
# DIFFERENT model re-grades triggered questions without seeing the first
# grade; disagreement flags the submission needs_review for the teacher.
# Grader A's score always stands — the second opinion can only flag.
GRADING_SECOND_OPINION_ENABLED = True
# Candidate models for grader B, in preference order. The first one that
# differs from the model that ACTUALLY graded (fallback routing included)
# is used; if none differs, the second opinion is skipped — a same-model
# "second opinion" shares every blind spot of the first.
GRADING_SECOND_OPINION_MODELS = ["deepseek/deepseek-v4-pro"]
# Trigger thresholds. A run below this confidence gets a full second
# read; individual questions trigger on a model-emitted flag_for_review
# or points >= the high-points threshold; and a small random sample of
# everything else keeps the easy cases measured.
GRADING_SECOND_OPINION_MIN_CONFIDENCE = 80
GRADING_SECOND_OPINION_HIGH_POINTS = 15
GRADING_SECOND_OPINION_SAMPLE_RATE = 0.05
# Disagreement severity tiers (teacher triage — never suppression): a
# disagreement whose point gap is >= critical_fraction of the question's
# points (or >= 2 rubric levels apart) is "critical"; >= moderate_fraction
# is "moderate"; smaller gaps are "borderline". Feeds review_severity
# ordering and the grading_eval segmentation.
GRADING_DISAGREEMENT_CRITICAL_FRACTION = 0.5
GRADING_DISAGREEMENT_MODERATE_FRACTION = 0.25

CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_RESULT_EXPIRES = 3600  # Delete results after 1 hour

WEEKLY_COURSE_SUMMARY_DAY_OF_WEEK = env.str(
    "WEEKLY_COURSE_SUMMARY_DAY_OF_WEEK", default="6"
)
WEEKLY_COURSE_SUMMARY_HOUR = env.int("WEEKLY_COURSE_SUMMARY_HOUR", default=7)
WEEKLY_COURSE_SUMMARY_MINUTE = env.int("WEEKLY_COURSE_SUMMARY_MINUTE", default=0)

AT_RISK_ALERT_HOUR = env.int("AT_RISK_ALERT_HOUR", default=6)
AT_RISK_ALERT_MINUTE = env.int("AT_RISK_ALERT_MINUTE", default=30)

TEACHER_INACTIVITY_ALERT_HOUR = env.int("TEACHER_INACTIVITY_ALERT_HOUR", default=6)
TEACHER_INACTIVITY_ALERT_MINUTE = env.int("TEACHER_INACTIVITY_ALERT_MINUTE", default=45)
TEACHER_INACTIVITY_THRESHOLD_DAYS = env.int(
    "TEACHER_INACTIVITY_THRESHOLD_DAYS", default=14
)

USE_BETA_PLAN_ON_SIGNUP = env.bool("USE_BETA_PLAN_ON_SIGNUP", default=False)

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    "record-concurrent-users-every-minute": {
        "task": "dashboard.tasks.record_concurrent_users",
        "schedule": 60.0,
    },
    # "reconcile-trial-expiration": {
    #     "task": "billing.tasks.process_subscription_renewals",
    #     "schedule": crontab(minute=0, hour=0),
    # },
    "process-license-renewals": {
        "task": "billing.tasks.process_license_renewals",
        "schedule": crontab(minute=0, hour=0),
    },
    "process-annual_plan-credit-grants": {
        "task": "billing.tasks.process_annual_plan_credit_grants",
        "schedule": crontab(minute=0, hour=2),
    },
    "process-license-monthly-credit-refreshes": {
        "task": "billing.tasks.process_license_monthly_credit_refreshes",
        "schedule": crontab(minute=0, hour=3),
    },
    "reconcile-subscriptions-daily": {
        "task": "billing.tasks.reconcile_subscription_renewals",
        "schedule": crontab(minute=0, hour=4),
    },
    # Watchdog over the Stripe webhook ledger: settles claims abandoned by
    # killed workers and raises an ERROR log for failures about to fall out
    # of Stripe's ~3-day retry window. Hourly, so a failure is always seen
    # with days to spare. Never re-runs handlers - see the task docstring.
    "sweep-stale-stripe-events": {
        "task": "billing.tasks.sweep_stale_stripe_events",
        "schedule": crontab(minute=15),
    },
    "cleanup-expired-credit-buckets": {
        "task": "billing.tasks.cleanup_expired_credit_buckets",
        "schedule": crontab(minute=0, hour=5),
    },
    "expire-active-trials": {
        "task": "billing.tasks.expire_active_trials",
        "schedule": crontab(minute=0, hour="*/6"),
    },
    "send-weekly-course-summaries": {
        "task": "dashboard.tasks.send_weekly_course_summaries",
        "schedule": crontab(
            minute=WEEKLY_COURSE_SUMMARY_MINUTE,
            hour=WEEKLY_COURSE_SUMMARY_HOUR,
            day_of_week=WEEKLY_COURSE_SUMMARY_DAY_OF_WEEK,
        ),
    },
    "send-weekly-student-summaries": {
        "task": "dashboard.tasks.send_weekly_student_summaries",
        "schedule": crontab(
            minute=WEEKLY_COURSE_SUMMARY_MINUTE,
            hour=WEEKLY_COURSE_SUMMARY_HOUR,
            day_of_week=WEEKLY_COURSE_SUMMARY_DAY_OF_WEEK,
        ),
    },
    "send-weekly-school-admin-summaries": {
        "task": "dashboard.tasks.send_weekly_school_admin_summaries",
        "schedule": crontab(
            minute=WEEKLY_COURSE_SUMMARY_MINUTE,
            hour=WEEKLY_COURSE_SUMMARY_HOUR,
            day_of_week=WEEKLY_COURSE_SUMMARY_DAY_OF_WEEK,
        ),
    },
    "send-at-risk-student-alerts": {
        "task": "dashboard.tasks.send_at_risk_student_alerts",
        "schedule": crontab(minute=AT_RISK_ALERT_MINUTE, hour=AT_RISK_ALERT_HOUR),
    },
    "send-teacher-inactivity-alerts": {
        "task": "dashboard.tasks.send_teacher_inactivity_alerts",
        "schedule": crontab(
            minute=TEACHER_INACTIVITY_ALERT_MINUTE,
            hour=TEACHER_INACTIVITY_ALERT_HOUR,
        ),
    },
}
CELERY_BEAT_SCHEDULER = "django_celery_beat.schedulers:DatabaseScheduler"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

#
# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     # ManifestStaticFilesStorage is recommended in production, to prevent
#     # outdated JavaScript / CSS assets being served from cache
#     # (e.g. after a Wagtail upgrade).
#     # See https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
#     },
# }

if ENVIRONMENT == "prod":
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": (
                "cloudinary_storage.storage.MediaCloudinaryStorage"
                if ENVIRONMENT in ["dev", "local"]
                else "django.core.files.storage.FileSystemStorage"
            ),
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": env.str("CLOUDINARY_CLOUD_NAME"),
    "API_KEY": env.str("CLOUDINARY_API_KEY"),
    "API_SECRET": env.str("CLOUDINARY_API_SECRET"),
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "AutoGrader.pagination.StandardPageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": (
        "users.renderers.APIJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "EXCEPTION_HANDLER": "users.exceptions.custom_exception_handler",
    "DEFAULT_ROUTER_TRAILING_SLASH": False,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

DJOSER = {
    "LOGIN_FIELD": "email",
    "USER_ID_FIELD": "id",
    "HIDE_USERS": True,
    "TOKEN_MODEL": None,
    "SEND_ACTIVATION_EMAIL": True,
    "SEND_CONFIRMATION_EMAIL": True,
    "ACTIVATION_URL": "activate/{uid}/{token}",
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": False,
    "LOGOUT_ON_PASSWORD_CHANGE": True,
    # Override the default Djoser serializers:
    # "SERIALIZERS": {
    #     "user_create": "users.serializers.CustomUserCreateSerializer",
    #     "user": "users.serializers.CustomUserSerializer",
    #     "current_user": "users.serializers.CustomUserSerializer",
    # },
    "EMAIL": {
        # "activation": "home.emails.ActivationEmail",
        # "confirmation": "home.emails.ConfirmationEmail",
        # "password_reset": "home.emails.PasswordResetEmail",
    },
    # Limit who can do what:
    # - Anyone can register
    # - Only authenticated users can retrieve/update themselves
    # - Only admins can list or delete other users
    # "PERMISSIONS": {
    #     "user_create": ["rest_framework.permissions.AllowAny"],
    #     "user": ["rest_framework.permissions.IsAuthenticated"],
    #     "user_list": ["rest_framework.permissions.IsAdminUser"],
    #     "user_delete": ["rest_framework.permissions.IsAdminUser"],
    # }
}

SPECTACULAR_SETTINGS = {
    "TITLE": f"GradeA+ Backend - {'Local' if ENVIRONMENT == 'local' else 'Dev' if ENVIRONMENT == 'dev' else 'Prod'}"
    " Environment",
    "DESCRIPTION": "The API backend for GradeA+",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/openapi/v1",
    "SCHEMA_PATH_PREFIX_TRIM": True,
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
    # "PREPROCESSING_HOOKS": [
    #     'UniSaas.schema.filter_admin_paths',
    # ],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "name": "Bearer",
                "bearerFormat": "JWT",
                "description": "Enter a valid JWT token as: **Bearer &lt;token&gt;**",
            }
        }
    },
    "SECURITY": [{"BearerAuth": []}],
    "SWAGGER_UI_SETTINGS": {
        "defaultModelsExpandDepth": -1,
        "defaultModelExpandDepth": -1,
        # "docExpansion": "none",
    },
    "EXTENSIONS": {
        "polymorphic_assignment": "assignments.schema.PolymorphicAssignmentExtension",
    },
}

# EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
# DEFAULT_FROM_EMAIL = "GradeA+ <samueleffiong80@gmail.com>"
# SUPPORT_EMAIL = "GradeA+@gmail.com"

EMAIL_BACKEND = "anymail.backends.mailersend.EmailBackend"
# DEFAULT_FROM_EMAIL = "GradeA+ <samueleffiong80@gmail.com>"
# SUPPORT_EMAIL = "support@test-65qngkdjmm3lwr12.mlsender.net"
SUPPORT_EMAIL = "support@gradeautomator.com"


# This must match the domain in your screenshot
DEFAULT_FROM_EMAIL = "Grade A+ <support@gradeautomator.com>"
# DEFAULT_FROM_EMAIL = "Grade A+ <support@test-65qngkdjmm3lwr12.mlsender.net>"

# ANYMAIL = {
#     "SENDINBLUE_API_KEY": env.str("SENDINBLUE_API_KEY"),
# }

ANYMAIL = {
    "MAILERSEND_API_TOKEN": env.str("MAILSEND_API_KEY"),
    # "MAILERSEND_API_TOKEN": env.str("MAILSEND_LOCAL_API"),
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": (
            env.str("REDIS_LOCAL_URL")
            if ENVIRONMENT == "local"
            else (
                env.str("REDIS_DEV_URL")
                if ENVIRONMENT == "dev"
                else env.str("REDIS_PROD_URL")
            )
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
        # Namespaces cache keys so wildcard delete_pattern calls (e.g.
        # "*user*") can only ever match cache entries — never Celery
        # broker/result keys living in the same Redis instance.
        "KEY_PREFIX": "gaplus",
    }
}

# django-redis defaults to SCAN COUNT=10, i.e. one network round trip per
# ~10 keys when delete_pattern walks the keyspace. Signal handlers call
# delete_pattern on every user/course/enrollment save, so on a remote Redis
# that default turns each save into seconds of scanning.
DJANGO_REDIS_SCAN_ITERSIZE = 100_000

CACHE_TTL = 60 * 5


GOOGLE_OAUTH_CLIENT_ID = env.str("GOOGLE_OAUTH_CLIENT_ID")
GOOGLE_OAUTH_CLIENT_SECRET = env.str("GOOGLE_OAUTH_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = env.str("GOOGLE_REDIRECT_URI")

FIELD_ENCRYPTION_KEY = env.str("FIELD_ENCRYPTION_KEY", "")

# MailerLite (https://developers.mailerlite.com) - syncs activated users to
# mailing list groups segmented by user_type. API key is optional; when
# unset, MailerLiteService silently no-ops so signup/activation never breaks.
MAILERLITE_API_KEY = env.str("MAILERLITE_API_KEY", default="")
MAILERLITE_GROUP_ID_TEACHER = env.str("MAILERLITE_GROUP_ID_TEACHER", default="")
MAILERLITE_GROUP_ID_STUDENT = env.str("MAILERLITE_GROUP_ID_STUDENT", default="")
MAILERLITE_GROUP_ID_SCHOOL_ADMIN = env.str(
    "MAILERLITE_GROUP_ID_SCHOOL_ADMIN", default=""
)

if ENVIRONMENT == "prod":
    STRIPE_PUBLIC_KEY = env.str("STRIPE_PUBLIC_KEY")
    STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY")
    STRIPE_WEBHOOK_SECRET = env.str("STRIPE_WEBHOOK_SECRET")
else:
    STRIPE_PUBLIC_KEY = env.str("LOCAL_STRIPE_PUBLIC_KEY")
    STRIPE_SECRET_KEY = env.str("LOCAL_STRIPE_SECRET_KEY")
    STRIPE_WEBHOOK_SECRET = env.str("LOCAL_STRIPE_WEBHOOK_SECRET")


ALLOWED_BUSINESS_EMAIL_DOMAINS = None
DISALLOWED_EMAIL_DOMAINS = [
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "outlook.com",
    "aol.com",
    "icloud.com",
    "mail.com",
    "protonmail.com",
    "zoho.com",
    "yandex.com",
    "live.com",
    "msn.com",
    "qq.com",
    "163.com",
    "mail.ru",
    "inbox.lv",
    "rediffmail.com",
    "lycos.com",
    "gmx.com",
    "fastmail.com",
    "hushmail.com",
    "yopmail.com",
]

# Domains exempt from the personal/business email restriction above -
# accepted for both individual teacher (personal) and school admin/licensed
# (business) account creation. Used for QA/testing addresses.
EXEMPT_EMAIL_DOMAINS = [
    "yopmail.com",
]


ENABLE_BILLING_TIME_TRAVEL = env.bool("ENABLE_BILLING_TIME_TRAVEL", default=False)

# Email domains whose NEW Stripe customers get a fresh Stripe Test Clock
# attached at creation. A Test Clock can only ever be attached when the
# customer is created, so without this the billing time-travel tool can
# never advance Stripe's clock for customers made through the normal
# checkout flow. Only takes effect when ENABLE_BILLING_TIME_TRAVEL is on
# AND the Stripe key is a test key. Empty (the default) means no customer
# ever gets one. Use "*" to cover every customer in a dedicated QA
# environment. Example: BILLING_TEST_CLOCK_EMAIL_DOMAINS=yopmail.com
BILLING_TEST_CLOCK_EMAIL_DOMAINS = env.list(
    "BILLING_TEST_CLOCK_EMAIL_DOMAINS", default=[]
)
