"""
Django settings for AutoGrader project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# import logging
import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from environ import Env

env = Env()
env.read_env(".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "\n\n{name} {levelname} {asctime} {module} {process:d} {thread:d} {message}\n\n",
            "style": "{",
        },
        "simple": {
            "format": "\n\n[%(asctime)s] %(levelname)s %(message)s\n\n",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "INFO",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": [
                "console",
            ],
            "level": "ERROR",
        },
        "ERROR_REPORT": {
            "handlers": ["console"],
            "level": "ERROR",
        },
    },
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")
FRONTEND_DOMAIN = env.str("FRONTEND_DOMAIN")

# SECURITY WARNING: don't run with debug turned on in production!
ENVIRONMENT = env.str("ENVIRONMENT")

if ENVIRONMENT == "prod":
    DEBUG = False
elif ENVIRONMENT == "dev":
    DEBUG = False
elif ENVIRONMENT == "local":
    DEBUG = True

APPEND_SLASH = False

ALLOWED_HOSTS = ["*"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https?://([a-z0-9-]+\.)?localhost(:[0-9]+)?$",
]

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = False
CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_filters",
    "djoser",
    "anymail",
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "rest_framework.authtoken",
    "rest_framework_simplejwt.token_blacklist",
    "django_extensions",
    "users",
    "classrooms",
    "assignments",
    "students",
    "grading",
    "ocr_processor",
    "ai_processor",
    "dashboard",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "users.middleware.UserActivityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AutoGrader.urls"
AUTH_USER_MODEL = "users.CustomUser"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "AutoGrader.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ENVIRONMENT == "local":
    DATABASES = {
        "default": dj_database_url.config(default=env.str("DATABASE_URI_LOCAL"))
    }
elif ENVIRONMENT == "dev":
    DATABASES = {"default": dj_database_url.config(default=env.str("DATABASE_URI_DEV"))}
else:
    DATABASES = {"default": dj_database_url.config(default=env.str("DATABASE_URI"))}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Celery Configuration Options
CELERY_BROKER_URL = (
    env.str("REDIS_URL")
    if ENVIRONMENT == "local"
    else env.str("REDIS_DEV_URL") if ENVIRONMENT == "dev" else env.str("REDIS_PROD_URL")
)
CELERY_RESULT_BACKEND = (
    env.str("REDIS_URL")
    if ENVIRONMENT == "local"
    else env.str("REDIS_DEV_URL") if ENVIRONMENT == "dev" else env.str("REDIS_PROD_URL")
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Celery Beat Schedule
CELERY_BEAT_SCHEDULE = {
    "record-concurrent-users-every-minute": {
        "task": "dashboard.tasks.record_concurrent_users",
        "schedule": 60.0,
    },
    # "send-email-task": {
    #     "task": "AutoGrader.tasks.send_email_task",
    #     "schedule": 60.0,
    # }
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

#
# STORAGES = {
#     "default": {
#         "BACKEND": "django.core.files.storage.FileSystemStorage",
#     },
#     # ManifestStaticFilesStorage is recommended in production, to prevent
#     # outdated JavaScript / CSS assets being served from cache
#     # (e.g. after a Wagtail upgrade).
#     # See https://docs.djangoproject.com/en/5.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
#     },
# }

if ENVIRONMENT == "prod":
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": (
        "users.renderers.APIJSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ),
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "EXCEPTION_HANDLER": "users.exceptions.custom_exception_handler",
    "DEFAULT_ROUTER_TRAILING_SLASH": False,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

DJOSER = {
    "LOGIN_FIELD": "email",
    "USER_ID_FIELD": "id",
    "HIDE_USERS": True,
    "TOKEN_MODEL": None,
    "SEND_ACTIVATION_EMAIL": True,
    "SEND_CONFIRMATION_EMAIL": True,
    "ACTIVATION_URL": "activate/{uid}/{token}",
    "USERNAME_CHANGED_EMAIL_CONFIRMATION": False,
    "LOGOUT_ON_PASSWORD_CHANGE": True,
    # Override the default Djoser serializers:
    # "SERIALIZERS": {
    #     "user_create": "users.serializers.CustomUserCreateSerializer",
    #     "user": "users.serializers.CustomUserSerializer",
    #     "current_user": "users.serializers.CustomUserSerializer",
    # },
    "EMAIL": {
        # "activation": "home.emails.ActivationEmail",
        # "confirmation": "home.emails.ConfirmationEmail",
        # "password_reset": "home.emails.PasswordResetEmail",
    },
    # Limit who can do what:
    # - Anyone can register
    # - Only authenticated users can retrieve/update themselves
    # - Only admins can list or delete other users
    # "PERMISSIONS": {
    #     "user_create": ["rest_framework.permissions.AllowAny"],
    #     "user": ["rest_framework.permissions.IsAuthenticated"],
    #     "user_list": ["rest_framework.permissions.IsAdminUser"],
    #     "user_delete": ["rest_framework.permissions.IsAdminUser"],
    # }
}

SPECTACULAR_SETTINGS = {
    "TITLE": f"GradeA+ Backend - {'Local' if ENVIRONMENT == 'local' else 'Dev' if ENVIRONMENT == 'dev' else 'Prod'}"
    " Environment",
    "DESCRIPTION": "The API backend for GradeA+",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/openapi/v1",
    "SCHEMA_PATH_PREFIX_TRIM": True,
    "COMPONENT_SPLIT_REQUEST": True,
    "COMPONENT_NO_READ_ONLY_REQUIRED": True,
    # "PREPROCESSING_HOOKS": [
    #     'UniSaas.schema.filter_admin_paths',
    # ],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "name": "Bearer",
                "bearerFormat": "JWT",
                "description": "Enter a valid JWT token as: **Bearer &lt;token&gt;**",
            }
        }
    },
    "SECURITY": [{"BearerAuth": []}],
    "SWAGGER_UI_SETTINGS": {
        "defaultModelsExpandDepth": -1,
        "defaultModelExpandDepth": -1,
        # "docExpansion": "none",
    },
}

EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
DEFAULT_FROM_EMAIL = "GradeA+ <samueleffiong80@gmail.com>"
SUPPORT_EMAIL = "GradeA+@gmail.com"

ANYMAIL = {
    "SENDINBLUE_API_KEY": env.str("SENDINBLUE_API_KEY"),
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": (
            env.str("REDIS_URL")
            if ENVIRONMENT == "local"
            else (
                env.str("REDIS_DEV_URL")
                if ENVIRONMENT == "dev"
                else env.str("REDIS_PROD_URL")
            )
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}
