# Generated by Django 5.2.6 on 2025-09-19 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classrooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="classroomsettings",
            name="classroom",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="classrooms.classroom",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="classrooms.classroom",
            ),
        ),
        migrations.AddField(
            model_name="studentsection",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="classrooms.section",
            ),
        ),
        migrations.AddField(
            model_name="studentsection",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="classroom",
            constraint=models.UniqueConstraint(
                fields=("teacher", "name", "academic_term"),
                name="unique_classroom_name_per_teacher_per_term",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("name", "classroom"), name="unique_section_name_per_classroom"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentsection",
            constraint=models.UniqueConstraint(
                fields=("student", "section"),
                name="unique_student_section_per_classroom",
            ),
        ),
    ]
