# Generated by Django 5.2.6 on 2025-10-09 12:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_remove_session_unique_academic_term_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
