# Generated by Django 5.2.6 on 2025-10-06 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0003_alter_classroom_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="section",
            name="unique_section_name_per_classroom",
        ),
        migrations.RemoveField(
            model_name="academicterm",
            name="type",
        ),
        migrations.RemoveField(
            model_name="section",
            name="classroom",
        ),
        migrations.AddField(
            model_name="academicterm",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_terms",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="academic_term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="classrooms.academicterm",
            ),
        ),
        migrations.AddConstraint(
            model_name="section",
            constraint=models.UniqueConstraint(
                fields=("name", "academic_term"),
                name="unique_section_name_per_classroom",
            ),
        ),
    ]
