# Generated by Django 5.2.6 on 2025-10-09 15:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0004_course_teacher"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="StudentSection",
            new_name="StudentCourse",
        ),
    ]
