# Generated by Django 5.2.6 on 2025-10-14 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0005_rename_studentsection_studentcourse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="course",
            name="unique_section_name_per_session",
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                fields=("name", "teacher", "session"),
                name="unique_section_name_per_session",
            ),
        ),
    ]
