# Generated by Django 5.2.6 on 2025-11-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0006_remove_course_unique_section_name_per_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcourse",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Enrolled"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("COMPLETED", "Completed"),
                    ("PENDING", "Pending"),
                ],
                default="ENROLLED",
                max_length=20,
            ),
        ),
    ]
