# Generated by Django 5.2.6 on 2025-12-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0007_remove_studentcourse_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcourse",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Enrolled"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("COMPLETED", "Completed"),
                    ("PENDING", "Pending"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
