# Generated by Django 5.2.6 on 2026-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0009_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentcourse",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("ENROLLED", "Enrolled"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("COMPLETED", "Completed"),
                    ("PENDING", "Pending"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
