# Generated by Django 5.2.6 on 2026-03-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0011_remove_course_categories_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="auto_added",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
