# Generated by Django 5.2.6 on 2026-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0012_studentcourse_auto_added"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourse",
            name="ai_summary",
            field=models.TextField(
                blank=True,
                help_text="AI-generated personalised summary of the student's performance in this course.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="studentcourse",
            name="ai_summary_generated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the last AI summary generation.",
                null=True,
            ),
        ),
    ]
