# Generated by Django 5.2.6 on 2026-07-28 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0013_studentcourse_ai_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="unique_session_name_per_teacher",
        ),
        migrations.AddField(
            model_name="session",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Audit: who created this session (admin or teacher).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="owner_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual Teacher"), ("SCHOOL", "School")],
                db_index=True,
                default="INDIVIDUAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only when owner_type = SCHOOL",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="classrooms.school",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner_type", "SCHOOL")),
                fields=("name", "teacher"),
                name="unique_session_name_per_teacher",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner_type", "SCHOOL")),
                fields=("name", "school"),
                name="unique_session_name_per_school",
            ),
        ),
    ]
