# Generated by Django 5.2.6 on 2026-07-28 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0014_remove_session_unique_session_name_per_teacher_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="session",
            name="unique_session_name_per_teacher",
        ),
        migrations.AlterField(
            model_name="session",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Audit trail of who actually created this session — the teacher for INDIVIDUAL sessions, or the school admin for SCHOOL sessions. Kept separate from `teacher` so a SCHOOL session's `teacher` field can stay null while still recording who made it.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="owner_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual Teacher"), ("SCHOOL", "School")],
                db_index=True,
                default="INDIVIDUAL",
                help_text="INDIVIDUAL = owned by a single teacher (no school). SCHOOL = created by a school admin and shared read-only with every teacher under that school.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="school",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only when owner_type=SCHOOL.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="classrooms.school",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only when owner_type=INDIVIDUAL.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner_type", "INDIVIDUAL")),
                fields=("name", "teacher"),
                name="unique_session_name_per_teacher",
            ),
        ),
    ]
