# Generated by Django 5.2.6 on 2026-08-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0015_remove_session_unique_session_name_per_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
