# Generated by Django 5.2.6 on 2026-08-04 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classrooms", "0015_remove_session_unique_session_name_per_teacher_and_more"),
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolAtRiskSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_date", models.DateField()),
                ("at_risk_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="at_risk_snapshots",
                        to="classrooms.school",
                    ),
                ),
            ],
            options={
                "ordering": ["snapshot_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "snapshot_date"),
                        name="unique_school_at_risk_snapshot_date",
                    )
                ],
            },
        ),
    ]
