# Generated by Django 5.2.6 on 2026-09-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_schoolatrisksnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentriskalertstate",
            name="alert_pending",
            field=models.BooleanField(default=False),
        ),
    ]
