# Generated by Django 5.2.6 on 2026-09-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_studentriskalertstate_alert_pending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentriskalertstate",
            name="alert_pending",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
