# Generated by Django 5.2.6 on 2025-10-09 14:43

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("subject_name", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("total_points", models.IntegerField()),
                ("question_count", models.IntegerField()),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("OBJECTIVE", "OBJECTIVE"),
                            ("ESSAY", "ESSAY"),
                            ("SHORT_ANSWER", "SHORT ANSWER"),
                            ("HYBRID", "HYBRID"),
                        ],
                        default="OBJECTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("questions", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Rubric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("criteria", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
