# Generated by Django 5.2.6 on 2025-09-14 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="extracted_data",
            new_name="questions",
        ),
    ]
