# Generated by Django 5.2.6 on 2025-09-15 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_rename_extracted_data_assignment_questions"),
        ("classrooms", "0002_section_description_alter_classroom_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="section",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="classrooms.section",
            ),
            preserve_default=False,
        ),
    ]
