# Generated by Django 5.2.6 on 2025-09-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="extracted_data",
            new_name="questions",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="description",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="file",
        ),
        migrations.AddField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="question_count",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="subject_name",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="assignment",
            name="total_points",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("OBJECTIVE", "Objective"),
                    ("ESSAY", "Essay"),
                    ("SHORT-ANSWER", "Short Answer"),
                    ("HYBRID", "Hybrid"),
                ],
                default="OBJECTIVE",
                max_length=20,
            ),
        ),
    ]
