# Generated by Django 5.2.6 on 2025-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_assignment_section"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("OBJECTIVE", "Objective"),
                    ("ESSAY", "Essay"),
                    ("SHORT-ANSWER", "Short Answer"),
                    ("HYBRID", "Hybrid"),
                ],
                default="OBJECTIVE",
                max_length=20,
            ),
        ),
    ]
