# Generated by Django 5.2.6 on 2025-10-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_rename_extracted_data_assignment_questions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("OBJECTIVE", "OBJECTIVE"),
                    ("ESSAY", "ESSAY"),
                    ("SHORT_ANSWER", "SHORT ANSWER"),
                    ("HYBRID", "HYBRID"),
                ],
                default="OBJECTIVE",
                max_length=20,
            ),
        ),
    ]
