# Generated by Django 5.2.6 on 2025-10-09 15:52
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="created_by",
            new_name="teacher",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="subject_name",
        ),
        migrations.AddField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(default=timezone.now),
            preserve_default=False,
        ),
    ]
