# Generated by Django 5.2.6 on 2025-10-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_rename_created_by_assignment_teacher_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignment",
            options={"ordering": ["title"]},
        ),
    ]
