# Generated by Django 5.2.6 on 2025-10-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_alter_assignment_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="estimated_time",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
