# Generated by Django 5.2.6 on 2025-11-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0006_assignment_estimated_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="estimated_time",
        ),
        migrations.AlterField(
            model_name="assignment",
            name="assignment_type",
            field=models.CharField(
                choices=[
                    ("OBJECTIVE", "OBJECTIVE"),
                    ("ESSAY", "ESSAY"),
                    ("SHORT-ANSWER", "SHORT ANSWER"),
                    ("HYBRID", "HYBRID"),
                ],
                default="OBJECTIVE",
                max_length=20,
            ),
        ),
    ]
