# Generated by Django 5.2.6 on 2025-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0007_remove_assignment_estimated_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
