# Generated by Django 5.2.6 on 2026-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0008_alter_assignment_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="extraction_confidence",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="potential_issues",
            field=models.TextField(blank=True, null=True),
        ),
    ]
