# Generated by Django 5.2.6 on 2026-01-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0009_assignment_extraction_confidence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="custom_ai_prompt",
            field=models.TextField(blank=True, null=True),
        ),
    ]
