# Generated by Django 5.2.6 on 2026-01-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0010_assignment_custom_ai_prompt"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="ai_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="ai_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="ai_raw_payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
