# Generated by Django 5.2.6 on 2026-01-26 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assignments",
            "0011_assignment_ai_generated_assignment_ai_generated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="was_overridden",
            field=models.BooleanField(default=False),
        ),
    ]
