# Generated by Django 5.2.6 on 2026-01-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0012_assignment_was_overridden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="ai_generated",
            field=models.BooleanField(default=True),
        ),
    ]
