# Generated by Django 5.2.6 on 2026-01-30 08:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0013_alter_assignment_ai_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="self_assessment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="potential_issues",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
