# Generated by Django 5.2.6 on 2026-01-30 08:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0014_assignment_self_assessment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="potential_issues",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
