# Generated by Django 5.2.6 on 2026-01-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0015_alter_assignment_potential_issues"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="extraction_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="extraction_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assignment",
            name="had_error",
            field=models.BooleanField(default=False),
        ),
    ]
