# Generated by Django 5.2.6 on 2026-02-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0016_assignment_extraction_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="grading_status",
            field=models.CharField(
                choices=[("NOT_STARTED", "NOT STARTED"), ("COMPLETED", "COMPLETED")],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
