# Generated by Django 5.2.6 on 2026-02-09 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0017_assignment_grading_status"),
        ("classrooms", "0011_remove_course_categories_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="classrooms.topic",
            ),
        ),
    ]
