# Generated by Django 5.2.6 on 2026-02-10 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0018_assignment_topic"),
        ("classrooms", "0011_remove_course_categories_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("course", "title"), name="unique_assignment_per_course"
            ),
        ),
    ]
