# Generated by Django 5.2.6 on 2026-02-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0019_alter_assignment_title_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="grading_status",
        ),
        migrations.RemoveField(
            model_name="assignment",
            name="had_error",
        ),
    ]
