# Generated by Django 5.2.6 on 2026-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0020_remove_assignment_grading_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="overridden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
