# Generated by Django 5.2.6 on 2026-02-17 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0021_assignment_overridden_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="raw_input",
            field=models.TextField(blank=True, null=True),
        ),
    ]
