# Generated by Django 5.2.6 on 2026-02-17 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0022_assignment_raw_input"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Rubric",
        ),
    ]
