# Generated by Django 5.2.6 on 2026-02-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0023_delete_rubric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="question_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="total_points",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
