# Generated by Django 5.2.6 on 2026-02-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0024_alter_assignment_instructions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="instructions",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
