# Generated by Django 5.2.6 on 2026-03-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0025_alter_assignment_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "DRAFT"), ("PUBLISHED", "PUBLISHED")],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
