# Generated by Django 5.2.6 on 2026-03-12 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0026_assignment_status"),
        ("classrooms", "0011_remove_course_categories_topic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignment",
            name="unique_assignment_per_course",
        ),
        migrations.AddField(
            model_name="assignment",
            name="raw_input_hash",
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.UniqueConstraint(
                fields=("course", "title", "raw_input_hash"),
                name="unique_assignment_per_course",
            ),
        ),
    ]
