# Generated by Django 5.2.6 on 2026-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0027_remove_assignment_unique_assignment_per_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="raw_input_hash",
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
