# Generated by Django 5.2.6 on 2026-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0028_alter_assignment_raw_input_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="auto_grade_on_due_date",
            field=models.BooleanField(
                default=False,
                help_text="If True, all ungraded submissions will be automatically graded when the due date passes.",
            ),
        ),
    ]
