# Generated by Django 5.2.6 on 2026-04-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0029_assignment_auto_grade_on_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "DRAFT"),
                    ("PUBLISHED", "PUBLISHED"),
                    ("UNPUBLISHED", "UNPUBLISHED"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
