# Generated by Django 5.2.6 on 2026-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0030_alter_assignment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="grading_task_name",
            field=models.CharField(
                blank=True,
                help_text="The name of the Celery task handling the batch grading",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="scheduled_grading_at",
            field=models.DateTimeField(
                blank=True,
                help_text="The time all submissions for this assignment are scheduled to be graded",
                null=True,
            ),
        ),
    ]
