# Generated by Django 5.2.6 on 2026-04-23 14:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0032_assignmentgenerationsession_and_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentGenerationHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "prompt",
                    models.TextField(
                        help_text="The original prompt sent to generate or extract the assignment"
                    ),
                ),
                ("assignment_snapshot", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameIndex(
            model_name="assignmentgenerationmessage",
            new_name="assignments_session_aea8e2_idx",
            old_name="assignmentg_session_b8f3ec_idx",
        ),
        migrations.RenameIndex(
            model_name="assignmentgenerationmessage",
            new_name="assignments_session_b9a269_idx",
            old_name="assignmentg_session_3ce73e_idx",
        ),
        migrations.RenameIndex(
            model_name="assignmentgenerationsession",
            new_name="assignments_user_id_30232d_idx",
            old_name="assignmentg_user_id_b13b45_idx",
        ),
        migrations.AddField(
            model_name="assignmentgenerationhistory",
            name="assignment",
            field=models.ForeignKey(
                help_text="The assignment generated from this prompt",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_history",
                to="assignments.assignment",
            ),
        ),
        migrations.AddField(
            model_name="assignmentgenerationhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_generation_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
