# Generated by Django 5.2.6 on 2026-07-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0033_assignmentgenerationhistory_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="admin_grading_notified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When school admins were notified that grading finished for this assignment. Also acts as an idempotency guard so the notification is only ever sent once per assignment.",
                null=True,
            ),
        ),
    ]
