# Generated by Django 5.2.6 on 2026-08-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0034_assignment_admin_grading_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="rigor_blooms_coverage",
            field=models.FloatField(
                blank=True,
                help_text="Fraction of question points that carried a recognised blooms_level, 0.0-1.0. Reported alongside the score so a confident-looking number drawn from sparse data is visible.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="rigor_demand",
            field=models.FloatField(
                blank=True,
                help_text="Points-weighted mean Bloom's taxonomy level across this assignment's questions, 0-5. Null when Bloom's coverage is below assignments.rigor.MIN_BLOOMS_COVERAGE.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="rigor_standards",
            field=models.FloatField(
                blank=True,
                help_text="Share of open-ended questions carrying a usable rubric, scaled 0-5. Null when the assignment has no open-ended questions.",
                null=True,
            ),
        ),
    ]
