# Generated by Django 5.2.6 on 2026-08-19 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0036_backfill_assignment_rigor"),
        ("classrooms", "0016_school_is_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["course", "title"], name="assignment_course_title_idx"
            ),
        ),
    ]
