# Generated by Django 5.2.6 on 2026-08-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0037_assignment_course_title_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
