# Generated by Django 5.2.6 on 2026-09-14 16:15

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0038_assignment_updated_at"),
        ("classrooms", "0016_school_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentUploadFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "PROCESSING"),
                            ("COMPLETED", "COMPLETED"),
                        ],
                        default="PROCESSING",
                        max_length=10,
                    ),
                ),
                ("claim_token", models.UUIDField(default=uuid.uuid4)),
                ("claimed_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_fingerprint",
                        to="assignments.assignment",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upload_fingerprints",
                        to="classrooms.course",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("course", "sha256"),
                        name="unique_upload_fingerprint_per_course",
                    )
                ],
            },
        ),
    ]
