# Generated by Django 5.2.6 on 2026-09-30 10:17

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0039_assignment_upload_fingerprint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
