# Generated by Django 5.2.6 on 2026-09-22 17:35

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("actor_id", models.UUIDField(blank=True, null=True)),
                (
                    "actor_role",
                    models.CharField(
                        choices=[
                            ("STUDENT", "Student"),
                            ("TEACHER", "Teacher"),
                            ("SCHOOL_ADMIN", "School admin"),
                            ("SUPER_ADMIN", "Super admin"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor_email",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("school_id", models.UUIDField(blank=True, null=True)),
                ("department_id", models.UUIDField(blank=True, null=True)),
                ("action", models.CharField(max_length=64)),
                ("target_type", models.CharField(max_length=64)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILURE", "Failure"),
                            ("DENIED", "Denied"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "error_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USER", "User"),
                            ("VALIDATION", "Validation"),
                            ("PROVIDER", "Provider"),
                            ("MODEL", "Model"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64, null=True)),
                ("trace_id", models.UUIDField()),
                (
                    "client_correlation_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("source_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "retention_class",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General (12 months)"),
                            ("STUDENT_RECORD", "Student record (3 years)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("before", models.JSONField(blank=True, null=True)),
                ("after", models.JSONField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["school_id", "-occurred_at"],
                        name="audit_school_time_ix",
                    ),
                    models.Index(
                        condition=models.Q(("department_id__isnull", False)),
                        fields=["department_id", "-occurred_at"],
                        name="audit_dept_time_ix",
                    ),
                    models.Index(
                        fields=["actor_id", "-occurred_at"], name="audit_actor_time_ix"
                    ),
                    models.Index(
                        fields=["action", "-occurred_at"], name="audit_action_time_ix"
                    ),
                    models.Index(
                        condition=models.Q(("reason_code__isnull", False)),
                        fields=["reason_code", "-occurred_at"],
                        name="audit_reason_time_ix",
                    ),
                    models.Index(
                        fields=["retention_class", "occurred_at"],
                        name="audit_retention_ix",
                    ),
                    models.Index(fields=["trace_id"], name="audit_trace_ix"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("actor_role", "STUDENT"), _negated=True),
                            models.Q(
                                ("actor_email__isnull", True),
                                ("source_ip__isnull", True),
                                ("user_agent__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="audit_student_no_pii_ck",
                    )
                ],
            },
        ),
    ]
