# Generated by Django 5.2.6 on 2026-09-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="actor_role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "Student"),
                    ("TEACHER", "Teacher"),
                    ("SCHOOL_ADMIN", "School admin"),
                    ("SUPER_ADMIN", "Super admin"),
                    ("SYSTEM", "System"),
                    ("ANONYMOUS", "Anonymous (not signed in)"),
                ],
                max_length=20,
            ),
        ),
    ]
