#!/usr/bin/env sh
# One git worktree per piece of work, so concurrent sessions stop fighting
# over a single staging area.
#
#   ./scripts/task-worktree.sh new    cache-invalidation
#   ./scripts/task-worktree.sh list
#   ./scripts/task-worktree.sh remove cache-invalidation
#
# WHY THIS EXISTS
# ---------------
# Git's index and stash are ONE mutable object per working tree. Two sessions
# in the same directory share them, and no amount of care fixes that:
#
#   * `git commit --amend` and `git reset` act on the whole index, so they
#     silently sweep in — or wipe — whatever anyone else had staged.
#   * `pre-commit` stashes ALL unstaged changes before running hooks and
#     restores them afterwards. If a second session is writing to those files
#     meanwhile, the restore collides. That is a work-LOSS risk, not just
#     confusion.
#   * Partial staging makes the staged tree differ from the working tree, and
#     hooks that scan the staged tree (detect-secrets) then disagree with the
#     files on disk about line numbers, forever.
#
# A worktree gives each task its own index, its own stash and its own HEAD,
# while sharing one object store — so no re-cloning and no disk bloat. Git
# also refuses to check out one branch in two worktrees, which forces the
# separate branches that stop history contention too.
#
# See docs/ops/parallel-sessions.md.
set -eu

ROOT=$(git rev-parse --show-toplevel)
PARENT=$(dirname "$ROOT")
PREFIX=$(basename "$ROOT")

usage() {
    sed -n '2,8p' "$0" | sed 's/^# \{0,1\}//'
    exit 64
}

[ $# -ge 1 ] || usage
CMD=$1

case "$CMD" in
list)
    git -C "$ROOT" worktree list
    exit 0
    ;;
new|remove)
    [ $# -eq 2 ] || usage
    TASK=$2
    ;;
*)
    usage
    ;;
esac

# Kebab-case only: the name becomes a directory, a branch and a Postgres
# database name, and each of those rejects a different set of characters.
case "$TASK" in
    *[!a-z0-9-]*|-*|*-|"") echo "task must be kebab-case, e.g. cache-invalidation" >&2; exit 64 ;;
esac

DIR="$PARENT/$PREFIX-$TASK"
BRANCH="task/$TASK"
# Postgres identifiers cap at 63 bytes and Django prepends "test_"; keep well
# clear of both.
TEST_DB=$(printf 'test_%s' "$TASK" | tr '-' '_' | cut -c1-40)

if [ "$CMD" = "remove" ]; then
    if [ -n "$(git -C "$DIR" status --porcelain 2>/dev/null || true)" ]; then
        echo "REFUSING: $DIR has uncommitted changes." >&2
        echo "Commit or discard them first — this script will not decide for you." >&2
        exit 1
    fi
    git -C "$ROOT" worktree remove "$DIR"
    git -C "$ROOT" worktree prune
    echo "Removed $DIR. The branch $BRANCH is kept — delete it yourself once merged:"
    echo "    git branch -d $BRANCH"
    exit 0
fi

# --- new ---------------------------------------------------------------
[ ! -e "$DIR" ] || { echo "$DIR already exists" >&2; exit 1; }

git -C "$ROOT" worktree add -b "$BRANCH" "$DIR"

# .env is gitignored, so a fresh worktree has none and Django cannot start.
# Symlinked rather than copied: secrets should live in one place, so rotating
# them does not mean hunting down N stale copies.
if [ -f "$ROOT/.env" ]; then
    ln -s "$ROOT/.env" "$DIR/.env"
    echo "linked .env -> $ROOT/.env"
else
    echo "WARNING: no .env at $ROOT — create one in the worktree before running anything." >&2
fi

# A per-worktree test database. Without this, two sessions running tests
# truncate each other's tables mid-run and produce failures that look like
# real bugs and are not reproducible.
cat > "$DIR/settings_worktree.py" <<EOF
"""
Test settings for the "$TASK" worktree. Generated by scripts/task-worktree.sh.

Exists for one reason: a UNIQUE test database name. Concurrent sessions
sharing one test database truncate each other's tables mid-run, and the
resulting failures look like real bugs but do not reproduce.

Redis needs no setting here. AutoGrader/settings.py gives every test
PROCESS its own cache key prefix and Celery broker/result-backend key
prefix, which isolates concurrent runs even within one worktree (H-9).
Do not point this worktree at a different Redis database number instead:
a database number is shared by every run that picks it.

    python manage.py test --settings=settings_worktree
"""

from AutoGrader.settings import *  # noqa: F401,F403
from AutoGrader.settings import DATABASES

DATABASES["default"].setdefault("TEST", {})
DATABASES["default"]["TEST"]["NAME"] = "$TEST_DB"
EOF

# settings_worktree.py is ignored via the tracked .gitignore rather than a
# per-worktree exclude file. Git reads info/exclude from the COMMON git dir,
# not from .git/worktrees/<name>/info/exclude — writing the latter looks
# right, changes nothing, and the generated file then shows up as untracked
# noise in every worktree. Verified empirically.

cat <<EOF

Worktree ready.

    cd $DIR
    git branch            -> $BRANCH
    test database         -> $TEST_DB
    tests                 -> python manage.py test --settings=settings_worktree

The virtualenv is shared (it lives outside the repo) so there is nothing to
install. Commit here as normal — this worktree has its own index, so nothing
you stage can collide with another session.

When the work is merged:
    ./scripts/task-worktree.sh remove $TASK
EOF
