# Generated by Django 5.2.6 on 2025-10-09 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ai_processor", "0001_initial"),
        ("classrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="classrooms.section"
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_processor.chatsession",
            ),
        ),
    ]
