# Generated by Django 5.2.6 on 2026-08-15 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_processor", "0004_chatsession_assistant_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BenchmarkRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("run_id", models.CharField(max_length=100, unique=True)),
                ("recorded_at", models.DateTimeField()),
                ("mode", models.CharField(max_length=20)),
                ("source", models.CharField(default="benchmark", max_length=30)),
                ("code_sha", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "prompt_fingerprint",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "dataset_fingerprint",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                ("is_full_run", models.BooleanField(default=True)),
                ("submissions", models.PositiveIntegerField(default=0)),
                ("submissions_failed", models.PositiveIntegerField(default=0)),
                ("questions_graded", models.PositiveIntegerField(default=0)),
                ("exact_rate", models.FloatField(blank=True, null=True)),
                ("within_one_level_rate", models.FloatField(blank=True, null=True)),
                ("mean_level_error", models.FloatField(blank=True, null=True)),
                ("evidence_verified_rate", models.FloatField(blank=True, null=True)),
                ("deterministic_accuracy", models.FloatField(blank=True, null=True)),
                (
                    "second_opinion_disagreement_rate",
                    models.FloatField(blank=True, null=True),
                ),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("archive_url", models.URLField(blank=True, max_length=500, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["mode", "recorded_at"],
                        name="ai_processo_mode_7a82aa_idx",
                    ),
                    models.Index(
                        fields=["prompt_fingerprint"],
                        name="ai_processo_prompt__f37efa_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BenchmarkQuestionOutcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_key", models.CharField(max_length=50)),
                ("student_key", models.CharField(max_length=50)),
                ("question_number", models.PositiveIntegerField()),
                ("question_type", models.CharField(max_length=30)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("expected_points", models.FloatField(blank=True, null=True)),
                ("awarded_points", models.FloatField(blank=True, null=True)),
                ("expected_level", models.IntegerField(blank=True, null=True)),
                ("awarded_level", models.IntegerField(blank=True, null=True)),
                ("level_error", models.IntegerField(blank=True, null=True)),
                ("verdict", models.CharField(blank=True, max_length=20)),
                (
                    "level_decision",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("graded_by", models.CharField(blank=True, max_length=100, null=True)),
                ("evidence_verified", models.BooleanField(blank=True, null=True)),
                (
                    "second_opinion_disagreed",
                    models.BooleanField(blank=True, null=True),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_outcomes",
                        to="ai_processor.benchmarkrun",
                    ),
                ),
            ],
            options={
                "ordering": ["assignment_key", "student_key", "question_number"],
                "indexes": [
                    models.Index(
                        fields=["assignment_key", "student_key", "question_number"],
                        name="ai_processo_assignm_42fce8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "run",
                            "assignment_key",
                            "student_key",
                            "question_number",
                        ),
                        name="unique_benchmark_question_outcome_per_run",
                    )
                ],
            },
        ),
    ]
